<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="brief-update"><a href="#brief-update">Brief Update</a></h1>
    <p>
      So we are moving providers. I would just like to inform the visitors should their be any disruption that I am
      doing an entirely unknown process and we will be seeing how it works.
    </p>
    <p>
      So far I&#39;ve had flawless domain service from Google Domains. It&#39;s really easy, the interface is quite
      simple yet its feature rich. The professionalism of the instant updates is just something else. It takes a while
      to perform these tasks so the fact that it happens like it does, its just splendid.
    </p>
    <p>
      They&#39;ve sold their service, which was in beta to begin with, to squarespace. They are another provider
      I&#39;ve seen and they look pretty nice. I&#39;ve noticed their services and products and they seem to function
      well.
    </p>
    <p>
      It wasn&#39;t until recently I&#39;ve decided to go with Shopify to complete all my purchase with my site. They
      are more closely alligned with my history, they are using tucows, based out of Canada and they provide a ton of
      support and API interface logic to handle transactions. They also provide tons of documentation. For all they are
      offering, I&#39;ve decided to give them a real concentrated effort. The technologies are open sourced and they are
      providing full documentation. In software terms, thats really all you can ask for and all you really need. They
      provide it, there is no mystery and attempted veil. They provide you with the freedom you desire. Whether or not
      that&#39;s able to be utilized properly? Well that&#39;s where I come in. Time to really get going and learn this
      stuff. It&#39;s finally at the level I&#39;ve always required in order to be able to compete with the bigger names
      out there. I mean, I&#39;m just one man, after all.
    </p>
    <p><ImgZoom src="/quick-update-oct2023/DMW-Blooper.webp">Happy Halloween.</ImgZoom></p>
  </article>
</Post>
