<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;

  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h1 id="we-kinda-got-mixed-up-and-turned-around">
      <a href="#we-kinda-got-mixed-up-and-turned-around">We kinda got mixed up and turned around</a>
    </h1>
    <p>
      Let&#39;s just ignore the fact that everything has become extremely strange lately. While we are at it, let&#39;s
      also ignore how everyone is just going for it. Against better judgments everywhere.... Let&#39;s try to just
      overlook these awkward, awkward things and resist the urge to just dive in....
    </p>
    <p><ImgZoom src="/new-year/1689880650728.gif" alt="How Strange"></ImgZoom></p>
    <p>
      It&#39;s the end of the year and it is time to reflect on how things went. For most of it, I&#39;ve spent my time
      ranting, raving, coding, and recovering. I did some serious time in the hospital due to an unknown pathogen.
      I&#39;m just happy to be feeling better, I took the prescribed medicine and it seems to be helping. I&#39;ve
      changed my eating habits because as much as it seems like the year 2000, it just isn&#39;t. I&#39;ve been eating
      so much hard foods and it just finally took it&#39;s toll. There are other factors that are ramping up the effects
      but I just need to make a change. I felt sick when drinking 7+ cups of coffee every day, all day. I should have
      paid attention instead of just eating something so I can drink more coffee. I&#39;ve always known I needed to cut
      back on my spices, my red meat intake and just about everything I was doing was dumb. I&#39;ve changed that and
      now I feel stronger and I actually feel normal as if I know what I am doing when ingesting vittles. I come from
      the fast food every night clan. That&#39;s how I used to live. Either fast food or microwave meals. Terrible
      habits I tell you that much.
    </p>
    <p><ImgZoom src="/new-year/a69abeb5c4dd6860c8b1a57e5f8d0ba1.gif" alt="Geico Pig Commercial Clip"></ImgZoom></p>
    <p>
      You would think it was 1999 the way everyone is going on. It&#39;s pretty cool though as long as we all just keep
      it simple. It was fun. I can&#39;t believe how in accordance everything was. It truly blew my mind to both witness
      and be part of something so great. It&#39;s all for a reason. We are not just tripping down memory lane, we are
      gauging how far we&#39;ve come and how much everything around us has changed. Some of us are reclaiming lost
      ideals while others are doing those things we always wondered about.
    </p>
    <p><ImgZoom src="/new-year/13583408667807162873.gif" alt="Smiley"></ImgZoom></p>
    <p>
      I got to have a really chilled out year, for what its worth, as many other people did not. I see now that there is
      a great deal of risk that is only apparent once you are in the proverbial fire so to speak. Living a good life,
      and living your best life, sticking to your ideals and just being a good person will prevent most of the pitfalls
      that are out there but they only go so far and you can ask only so much. You just have to learn to accept what you
      are dealing with and build from it. Your situation and problems exist regardless of the form they take. Try to
      remember that when dealing with solutions. I did and it all seems a whole lot less personal now. It&#39;s nice.
    </p>
    <ul>
      <li>
        Giscuss, the comments section on this site, is currently down globally which means I have no control over it.
        It&#39;s open source so we will just have to wait for a fix to be implemented.
      </li>
      <li>
        Musicvidz is coming to a completion, the project will be replaced by a more modernized version with newer
        features and a sleeker interface like a pirate TV station underground in a mad scientist&#39;s sewer layer.
      </li>
      <li>
        I lost the source code to nexflix, as well as my entire back up. my brand new 5tb western digital ruggedized
        external the entire thing. So I have to start from scratch it remains untouched and untouchable.
      </li>
      <li>still dont have work. Things are pretty hard to sell that were once real easy.</li>
      <li>still have all kinds of issues and stuff but I am starting to see everyone is having these same issues.</li>
      <li>my outlook is still positive for the future. I still have motivation to succeed.</li>
    </ul>
    <Youtube id="fOj-M19AiIY" />
  </article>
</Post>
