<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;

  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h2 id="the-discovery"><a href="#the-discovery">The Discovery</a></h2>
    <p>
      So, upon dealing with all this bullshit I started to do some searching and noticed some stuff I&#39;m not to happy
      with. First and foremost is the discovery of a local crime ring. They have people infiltrating every position so
      they can easily move you around where they want you. They demonstrated this to me, they could make me disappear by
      placing me into the mental institute where no one would know where I was. I know that nearly everyone involved in
      the decision making process on that occasion is part of the same crime ring. They are known accomplices and they
      are tied together by prostitution, sex, drugs, and violence (murder, rape, attacks, etc). None of them are what
      you could consider victims and they are all acting out of their own accords. They seem almost happy to be a part
      of it, sacrificing any and all parts of their lives just to live out this strange crime ring fantasy they have.
    </p>
    <p>
      It&#39;s a known fact that these people use drugs, participate in prostitution and they justify it many different
      ways. They&#39;ve been identified by their cohorts, most of whom where placed there to monitor them in the first
      place. They let these people loose and just have you steer clear of them if you can. I can understand there is no
      place for them and they are manipulative in such ways that imprisonment odds seem very unlikely.
    </p>
    <p>
      These people are mostly cocaine abusers. That&#39;s the main driving force as far as income and dangling a carrot
      over people&#39;s heads. Doing some digging on these people they all seem to arrive and interact at the same
      times. There are no odds that just doesn&#39;t happen. Then there are the identities, these are almost always fake
      they have no proper history other than a flimsy past however there is nothing that would indicate any intention to
      create a living. It all seems so very temporary.
    </p>
    <p>
      The motivation these people have is lacking that which they claim. They will have all these ambitions and things
      going on that require a tight knit contingency yet they lack the skills needed to even initiate such a thing.
      There is always a driving force controlling what they can and can&#39;t do, it&#39;s never their own decision and
      they are constantly checking permission to even look in a direction.
    </p>
    <h2 id="plans-of-action"><a href="#plans-of-action">Plans of action</a></h2>
    <p>
      What to do? Well, I&#39;ve been thinking about who I can come to and approach with this information and I&#39;ve
      really been searching and so far? I&#39;ve found that these people here are all just straight trash. I
      wouldn&#39;t approach them to ask for directions let alone ask for help. They are just idiots who can&#39;t even
      believe anything is even happening to begin with. They all claim with flags and slogans and memes to be a part of
      something bigger but when it comes down to it? They are just posers.
    </p>
    <p>
      It goes all the way up, these people are infiltrating law enforcement they are using them as if they are pawns. I
      already did my part as far as trying to report whatever the hell it is. I&#39;d be a damned fool if I pursue this
      any further as it&#39;s just at a stalemate for me. Without taking drastic actions, there is not much I can do.
    </p>
    <p>
      It&#39;s exactly like I&#39;ve said all these years. It turned out exactly as I predicted. They aren&#39;t really
      coming out ahead and their lives are filled with regret and suffering. They made these choices and hurt people who
      have done nothing but help them. They did this stuff on purpose thinking if they did it would benefit them
      somehow. We are talking about the really weak, bad ones here. No one argues on that point these people are beyond
      corrections they will never be correct. You can attempt to correct them but that will just be your correction, not
      theirs.
    </p>
    <p>
      So what does one do? Not much. I have had it and am just prepared to stand my ground. I just have to take the
      appropriate action to make them stop committing the crimes against me whatever it takes to do that. It&#39;s their
      choice they don&#39;t have to harass and stalk me like they are doing but they choose to do so. They don&#39;t
      even have to interact with me but they are actively searching me out and stalking my every move.
    </p>
    <p>
      These kinds of things just don&#39;t happen they&#39;ve been letting them go on for years. They are probably
      holding some stuff over these people&#39;s heads or they are part of it themselves. It&#39;s not my place to go
      out and find out what the hell you people have gotten yourselves into. This is an obvious fallacy and it needs to
      be dealt with immediately.
    </p>
    <p>
      The entire process where I thought I was being poisoned was to their advantage. They were able to poison me and
      punish me as if it&#39;s my fault so I stop reporting poisonings. Law enforcement is just a piece of shit. Most of
      the people involved are criminals anyway they are known and they aren&#39;t even able to make their own decisions.
    </p>
    <p>
      I&#39;d recommend that any citizen be very careful when dealing with this town. Businesses are not immune. These
      people are just straight up criminals begging to be shot. When it happens they are actually surprised. It&#39;s
      mostly due to all the cocaine and methamphetamine they are giving these people around here. Everyone has a heroin
      problem and is dying from it and its just easy to get these people just openly talk about and do it. That&#39;s no
      accident, it doesn&#39;t happen overnight, and it&#39;s not like no one noticed.
    </p>
    <p>
      That&#39;s just another one of the major problems the defense industry brings with it. We live next to a military
      base.
    </p>
    <Youtube id="n_wSYs5MvQc" />
  </article>
</Post>
