<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;

  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h1 id="rain"><a href="#rain">Rain</a></h1>
    <p>
      It rained a lot this week and weekend. It&#39;s the first time in a while I lost track of the days. I have been
      doing pretty well keeping up with them up until this past weekend. I noticed that it was unusually busy so it must
      have been the weekend. This town&#39;s activity comes in bursts of waves. They ripple out as well. I have been
      sitting here just watching the rain fall without even looking at it.
    </p>
    <p>
      I&#39;ve been doing a lot of driving lately. I went to all the places I grew up or spent some time at. It was
      quite overwhelming to see some of those places especially when you aren&#39;t expecting anything and all of the
      sudden a sensation or an old memory will come rushing back. It looks slightly bigger if one can believe that.
      I&#39;m not sure if at the time I just was so bored with life everything seemed so small or if it&#39;s just the
      same as usual or what. I don&#39;t really care enough to find out. I don&#39;t want that little magical feeling to
      dissipate or leave me when I start figuring out what everything means. It&#39;s fun, I didn&#39;t get a chance to
      do all these things growing up. I&#39;m glad I am finally becoming human. At least, that&#39;s how it feels.
    </p>
    <p>
      I know I don&#39;t do things in the traditional sense as it were around here. People are stunned and confused
      until they use the tool they have sitting atop their shoulders. Then they start to realize it&#39;s actually a
      right way to do things when they can&#39;t find any faults with it.
    </p>
    <h1 id="tragedy"><a href="#tragedy">Tragedy</a></h1>
    <p>
      I got some bad news. Bad news but good to hear. A lot of things are changing and have changed. People who treat
      others poorly and who have created so many problems, stolen, and so much more are dead, gone, and going. It&#39;s
      true, it may seem like forever when you are going through it. Once it&#39;s over, you are realizing exactly how
      much of that was just in your own head. I always used to think that when I found someone who was a real piece of
      crap that I would just end them and that&#39;s it, plain and simple. But it&#39;s just not like the movies. These
      are people with lives and they are all something more than just someone to be conquered or someone to defeat. They
      have lives. They shouldn&#39;t even exist at such a level but we give them that life when we pay mind to whatever
      they are trying to do. It&#39;s always just some bullshit with certain people and not accepting that can prove
      fatal.
    </p>
    <p>
      A lot of times, I wouldn&#39;t accept the negative outcome and I would try everything in my power to change things
      for the better. Most time, successfully I might add. That wasn&#39;t even the issue. Doing things the correct way
      was never the issue, something I failed to realize. I do, however, realize that now. We have to go through losses
      and suffer negative outcomes. It&#39;s simply part of life.
    </p>
    <h1 id="research"><a href="#research">Research</a></h1>
    <p>
      I&#39;ve been doing some research on the town and everything with social media. I was around during the ICQ days.
      IRC as well. ICQ was the instant messenger branded program, sold to Russia now. Still operating but entirely
      different. It was a real WinSOCKS champion with DCC features and stuff that just worked for file transfer. Multi
      protocol and really globally connected. Then there was IRC which was a multi platform, globally accessible chat
      protocol available on linux as well as windows.
    </p>
    <p>
      I see some of the same people on there now as always and some are different. There was never any online stuff like
      that it was all at parties and they just took the photos, that was where most of the life was in those photos. We
      went to a lot of the parties and they were really awful and troubling. It was a horror show for the most part so I
      don&#39;t know what people think, but from the looks of things those were just the actual best moments, most are
      fake, and most are just bursts of energy like that specifically for the photo.
    </p>
    <p>
      I see that someone who was supposed to be cool, was really down to get me this whole time. But he&#39;s dead now,
      fortunately. I was never treated well, I never had much to do other than them piling in the car, hanging out for a
      few and then me leaving and just smiling after having a nice pleasant time. I never did anything to anyone and I
      just had a lot of real bad issues that if they would have helped me, they wouldn&#39;t be in a lot of the shit
      they found themselves in. Cause what affects one of us, affects us all to some degree. Whether we like it or not.
      I never had much opportunity to even be friends with anyone let alone hang out.
    </p>
    <h1 id="activity"><a href="#activity">Activity</a></h1>
    <p>
      In case anyone was wondering what I&#39;ve been up to since I broke up with my ex and completely sold all my
      devices and went offline and lived in a tent in my room for a few years... well? Actually quite a lot. I&#39;ve
      learned a lot after being on my own. I originally had a fight with my ex, Gena, and we were together for 12 years.
      The last few of those years we were together, but apart. I was faithful the time we were together. I&#39;ve only
      been with 2 women in my entire life. All long term. I dated one other person for a day but that&#39;s just my one
      learning experience that people aren&#39;t objects as much as the internet and those groups will have you believe.
      If they start trying to categorize you as a race or a type or whatever? Run. It&#39;s never good, it&#39;s never
      genuine, and they are always out to get you. I was brainwashed into thinking it&#39;s a competition. It&#39;s not.
      People are not objects, and are not to be treated as such.
    </p>
    <p>
      Those people are hurt and just want to hurt others. There is no friendly whatever, it&#39;s all designed to hurt
      someone.
    </p>
    <p>
      I&#39;ve been searching for answers and trying to move on. I was hoping after a certain amount of time she would
      check back and see how everything was with the person she spent time with for 12 years, but I haven&#39;t heard a
      thing from her. Finding that strange, and being blasted with this Jenna Ellis news story, and other items, I
      decided to check her out. She seemed like she needed space and I gave her space for 12 years they told me where
      she was and I don&#39;t even remember that&#39;s how much space I gave. I went back on Facebook and it&#39;s just
      an entirely fake bunch of pages.
    </p>
    <p>
      I realized all that Facebook stuff was fake designed to hurt me. It was just an attack and I was attacked, and
      that was it. Someone with some type of skills, attacked me and I lost everything. There is no lawyers, there is no
      justice, just ask around. None of these poor and desperate people chose to be like they are they are all attacked.
      They were kited out to the middle of nowhere in their lives, and attacked. That&#39;s just what they do around
      here. It&#39;s a beast.
    </p>
    <p>
      Most of these people are just liars, thieves, and just are terrible people. I always thought they would do some
      kind of turn around move and everything would be cool. It turns out, they are just murderers.
    </p>
    <h1 id="recovery"><a href="#recovery">Recovery</a></h1>
    <p>
      I was hit with a terrible virus or something bad. This coronavirus stuff was just part of it. The bird flu, the
      swine flu, all that crap was around the same time I had some type of virus as well. I&#39;m not saying I had
      those, but I&#39;m not saying I didn&#39;t. I am not sure. I&#39;m finally feeling better, recovering. There was
      something wrong with my ears. Someone did something to me and that&#39;s just now getting better. I&#39;m taking a
      lot of Epsom salt baths. So I&#39;m just now getting better I really hadn&#39;t been well enough to do all the
      things I&#39;m now able to do. I tried, I had my moments but always fell back ill.
    </p>
    <p>
      It was in the food for sure, especially the niche things that I bought they were tracking me or something. Yes,
      they do that kind of stuff. The supermarket is one the most heavily surveiled places in America, second only to
      wall street. It&#39;s no stretch to be tailed, followed, and tracked. We were well aware they were doing it, just
      unaware of how they actually did it.
    </p>
    <p>
      They&#39;re discovering it&#39;s in the flavoring agents, the flavanoids, the spices, all that. It&#39;s in the
      ingredients, every chance they get. We are just now becoming aware of all this stuff and they are fighting to
      clean the supply lines. You can&#39;t compromise, when you do, when you purchase counterfeit items? That&#39;s
      when you give them the opportunity to advance.
    </p>
    <p>So I&#39;m feeling better, I&#39;m not accepting any more foolishness.</p>
    <h1 id="plans"><a href="#plans">Plans</a></h1>
    <p>
      Well, I want to do some work, I need an agent or some type of manager. I am not good at PR or SEO still. I
      don&#39;t really think anyone is, as it&#39;s such a trying time in general for such things. I&#39;m just trying
      to figure things out now and just chill and move on. I don&#39;t really have any plans and I don&#39;t plan to.
    </p>
    <Youtube id="PSz7Y8hAdlc" />
  </article>
</Post>
