<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="internet-freedom"><a href="#internet-freedom">Internet Freedom</a></h1>
    <p>
      <strong>Something we often</strong>
      take for granted is our internet freedom. All around us are name brands that represent years of influence and struggle
      even if the companies themselves do not. We have a choice to use these brands sometimes or we can make other decisions.
      Why do these choices feel so important even though we are constantly being told they don&#39;t? Brands represent a
      culmination of the past economy and the struggles they&#39;ve alleviated to attain their iconic logos. They very seldom
      represent an actual idea or a stance as they are portrayed. The task of indoctrination is left up to marketing as tastes,
      much like people&#39;s viewpoints, often change.
    </p>
    <p>
      I&#39;ve had the pleasure of being able to express my freedom by being able to look behind the veil of secrecy and
      have a fully transparent view of the lay of the land as it were. While the specifics still remain shrouded in
      mystery as they are completely devoid of relevancy, the bigger picture has most definitely been painted.
    </p>
    <p>
      To love one&#39;s own country does not mean a hatred for others. This is often jumbled up when we are left
      defending our country against others and we mix up our appreciations and distastes. Never has hatred stood on
      it&#39;s own for long when one has had time to sit back and think about the situation. A love of one&#39;s country
      means an appreciation for what works. The distaste is left to when we recognize traits we&#39;ve learned to
      outgrow or see as incorrect. Often times, our distastes are the same as the countrymen who inhabit that land. They
      are more than likely feeling the same way about their country&#39;s policies that we are. The same can be said
      about the inverse, they probably look at our policies and develop a distaste for Americans in general. Whereas
      most Americans, the majority, also oppose these policies. If we remove the imaginary boundaries that divide us, we
      can see we all have the same hopes and dreams deep down. While we may be learning different paths in life, it does
      come down to a similar view point of either life or death.
    </p>
    <p>
      In life, there is no middle point. Either you are moving or you are dead. That&#39;s just how it is. The same can
      be said about electronic life on the internet. It&#39;s constantly evolving and so are the brands. What once was
      supposed to be an American family household name, we&#39;ve found out is just a clever trick from a larger entity.
    </p>
    <p>
      We&#39;ve found out that immovable objects aren&#39;t immovable forever online. Similar to celebrity and fame,
      once they&#39;ve completed their purpose these things do not have the power to stand on their own. Investors learn
      that the hard way when the fun is over and they use past performance to dictate how the future will behave. It
      just isn&#39;t going to happen. The best thing that they can hope for, is a misreading that&#39;s it. All the data
      points cannot help anyone if they are unable to fully utilize them.
    </p>
    <p>
      We must remember that at times using things does not mean our support for them. We can use certain services
      without having to pick a side. That is what freedom is all about. All we have to do is keep true to our ideals and
      voila! The rest of the world has to either adapt or die trying. That&#39;s the way of the world. If you have a
      solid foundation, it&#39;s a lot easier to stand firm and true. Especially if your ideals are pure and are of good
      intent.
    </p>
    <p><ImgZoom src="/know-thyself/perl600span.webp" alt="Flag"></ImgZoom></p>
  </article>
</Post>
