<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;

  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h2 id="well-well-well"><a href="#well-well-well">Well, well, well...</a></h2>
    <p>
      All this talking and postering was all for show. These people turned out to all be treasonous fools working with
      the enemy to ensure our downfall. They are to be eliminated at once and that&#39;s no joke.
    </p>
    <p>
      This place has proven to be nothing but a disaster. The lies upon lies and foolish showmanship of pretty much
      nothing. They promise everything and deliver nothing. But they actually deliver it all neatly wrapped up as if
      doing so is some type of accomplishment that should be celebrated. You should see the look on their face when they
      realize it&#39;s not.
    </p>
    <p>
      I&#39;ve learned a few things with my short time here on earth and I&#39;d like to say that most of them are bad.
      They are of the category: WHAT <em>NOT</em>
      TO DO.
    </p>
    <p>
      That doesn&#39;t give me a right to just start getting upset and treating people poorly. It does, however, give me
      full rights and access to a path that includes moving forward without worrying about anyone else. Which, again,
      you should see the look on their faces when they realize what that all entails. Some people have just been
      coasting and we try to reason with them to do what we are all doing and they take that as an opportunity to just
      act as horrible as they can. They realize finally someone is paying attention to them and they are going to use
      that as an opportunity to impress those who only wish to do them harm.
    </p>
    <h2 id="discoveries"><a href="#discoveries">Discoveries</a></h2>
    <p>
      I made some <em>important</em>
      discoveries recently. I&#39;m not going to go into detail because I am unsure of the specifics at this moment in time
      and I can&#39;t speak clearly upon what I know is true. The diet is the most important one. I thought I was being poisoned
      by cigarettes and vape juice but that wasn&#39;t even the half of it. I was straight up poisoned by food! Stuff you
      buy at the groccery store? Well, there you have it. Once you rely on food as a primary substance? That&#39;s the moment
      it becomes scarce because it cannot become something it&#39;s not. Once you start packaging food as fun? That&#39;s
      your downfall. Almost all these packages are indicators of death. Once you realize what it truly is, you can see it
      a bit more clearly and it&#39;s real. While you may not notice the effects right away, you will soon start to feel
      ill and like everyone else, the reason will not be apparant until it&#39;s all but too late.
    </p>
    <p>
      This took me by surprise. I could not fathom it and I am 40 years old. I couldn&#39;t even imagine getting
      poisoned going to the store? no way. But it&#39;s true. Especially nowadays. I would not have ordered and eaten
      anything from Amazon until I was just so used to ordering from them I kind of did it by accident. It was not a
      pleasant experience. These food items sit in a wharehouse and who knows what the heck happens from there on. Other
      products could be leaking anything from aeresoled H2O, to toxic radiation! We aren&#39;t quite sure and then they
      only tell us after the fact. Other vendors routinely sabotage other sellers inventory. The list goes on why you
      should not order it and only one good reason is hunger. I became very ill from all these items and now can tell
      instantly if they are good or bad.
    </p>
    <p>
      Common sense dictates that if you are eating food that routinely says on it, &quot;Made in a factory that contains
      peanuts.&quot; and you aren&#39;t eating one thing that contains peanuts, thats just on there for plausibility.
      It&#39;s placed there so they are able to deny any wrong doing. We can&#39;t prove one thing or another but we
      know that is code language for dirty. Fine quality products are clean and that should be the standard. It actually
      is the standard. Only at places near the defense industry do you find this counterfeit materials and goods. Very
      rarely do citizens attempt to pull any of this off as they simply create their own and take pride in that. It
      takes more work to counterfeit something than it does to actually create a new product. There is a reason and its
      stolen credibilty usually to be able to deliver poison easier.
    </p>
    <p>
      Anytime you try to voice concerns lately, you are whisked away to the mental facility or threatened. Most recently
      I had my food benefits cut and have been threatened.
    </p>
    <p>
      It&#39;s a shame, I am shuttering my attempt at opening a business these people are all criminals and have no
      money. They are addicted to drugs and constantly attempt to steal from each other. None of these people are
      legitimate at anything they do and all my dealings have been because I&#39;ve been attacked. Well, we&#39;re all
      fed up with it and people are slowly starting to learn. Others have had to tap out and forfeit any chance at a
      real life because they are so far gone.
    </p>
    <p>
      I&#39;ll have nothing to do with any of that crap. I never have and don&#39;t plan to. I have never done anything
      wrong, I don&#39;t make poor choices and it is paying off in spades. I am enjoying that, I just wish I could get
      some WORK. I love fixing computers and can make them run perfectly. I&#39;d like to get back to that I haven&#39;t
      done much work since the coronavirus hit. I&#39;m anxious to get back to work besides just home repairs and
      landscaping. I haven&#39;t had any luck selling stuff and neither have a lot of other people from the looks of the
      markets.
    </p>
    <p>
      Hopefully with all the improvements that will bring much needed vocational assignments we can all take part in. I
      have faith things will improve. Just not here.
    </p>
    <Youtube id="teNvl4q43TM" />
  </article>
</Post>
