<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="telegram-messenger"><a href="#telegram-messenger">Telegram Messenger</a></h1>
    <p>
      I&#39;ve decided to give telegram messenger a try. I&#39;ve been reading the way it works compared to the rest and
      there is really no other choice for encrypted messaging. Signal is nice, they are all nice, however they do not
      meet the privacy standards. Telegram does. Or at least it seems to, what can one be truly certain of?
    </p>
    <p>
      I&#39;ve used them all. I&#39;ve been using encrypted messaging since day one simply because I&#39;m the target of
      crazy lawmen, just like the rest of America. Not only that, but I am the target of hackers, criminals, and just
      about anyone who is snooping in on conversations when you are sending messages in plain text? It&#39;s certain
      that anyone can read them. We just don&#39;t discuss it.
    </p>
    <p>
      That&#39;s why I&#39;ve been a staunch advocate of privacy since day one because it just isn&#39;t right. The
      solution is so easy, it should be mandatory, however, they must want an economy of spies.
    </p>
    <h2 id="making-the-switch"><a href="#making-the-switch">Making the Switch</a></h2>
    <p><ImgZoom src="/telegram/Y2MIPGOKEZJ7FJBUKZ5O7SEKRE.avif" alt="Telegram Messenger"></ImgZoom></p>
    <p>
      SO... Telegram it is. All of you that look at encrypting messages as if they are some type of evil, I beseech you
      to please take into consideration the fact that regular communication can be often overlooked and misinterpreted.
      For instance, two parties can keep a secret without having to say anything. This is left up to chance to decide
      who gets to have encrypted conversations due to a roll of the dice who will figure it out or not. Encryption
      simply ensures that a level playing field is accomplished when wanting a secure line of communication for the
      average person.
    </p>
    <p><ImgZoom src="/telegram/R1605G_BIRKINSHAW-383x215.jpg" alt="Sinking Ship"></ImgZoom></p>
    <p>
      I use it mainly for my family. I talk about sensitive subjects between family and I wouldn&#39;t want someone who
      shouldn&#39;t know that stuff knowing it... RIGHT? So that&#39;s the main and really my only reason. I pretend
      that I am some type of big shot needing encryption but the truth is, I don&#39;t even have someone to test out
      telegram with properly... so.
    </p>
    <h1 id="surfshark-update"><a href="#surfshark-update">SurfShark Update</a></h1>
    <p>
      <ImgZoom src="/telegram/08aff3a22157204b3d6c26b4e1a70cc041216bb8.avif" alt="Surfing With The Shark"></ImgZoom>
    </p>
    <p>
      I think this image came from digital ocean when I hit a 404 or something. Heh, but I am still surfing with the
      shark. It&#39;s a fine program and has worked BEYOND expectations. I&#39;m pleased. I will be returning and
      recommending this program. I&#39;ve been using it to read news and watch YouTube and I can tell it is working
      perfectly I&#39;ve been so safe. I&#39;ve <em>really</em>
       tested the limits of this thing as far as freedom goes. It&#39;s perfect. It really illustrates a point that at any
      time what you think is true, is just not so. Really just drives it home.
    </p>
    <p>
      They mainly target me with hacking and ads and such like that. Stuff to embarrass and enrage me. Surfshark
      prevents that. Even the mind games are ineffective. I know the technology works I can see the results. It opened
      my eyes, I have a clearer world view and my freedom is enhanced and becomes prospective again.
    </p>
    <p>It&#39;s slight little changes, its the proper choices that make all the difference in the world.</p>
    <p>
      <ImgZoom
        src="/telegram/2aRc9MSDbkH-s6Do22mzH45FhTjzOA4blBDDX7HcINvWLGytrrcOeb9bhVCTT6cuNZitClC7ENABvkMBwkMQQLiZWjoSEjPpVXuJkA.avif"
        alt="Mandala"></ImgZoom>
    </p>
  </article>
</Post>
