<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;

  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h2 id="chains"><a href="#chains">Chains</a></h2>
    <p>
      A lot of times in my life I have advocated for people&#39;s release and for their freedom. Mostly, I put myself in
      their position and as someone who is innocent of their situation I couldn&#39;t understand why they would want to
      imprison me. Or at least that&#39;s the situation and how it seems. From the early days of Kevin Mitnick, the
      fellow hacker who merely got a leg up and the man didn&#39;t appreciate his intelligence to the friends I was
      supposed to have, there have been many attempts to sway my sense of justice and warp my perceptions.
    </p>
    <p>
      Not being real experienced as a child, I wasn&#39;t aware of all the manipulations and straight up tyrannical
      efforts to change my perceptions into that of something less desirable. They are trying to make me excuse bad
      behavior. Not me personally, but in all the mix up it would appear that way.
    </p>
    <p>
      I read a lot and I have a very active imagination. That&#39;s not to say I hear and see things that aren&#39;t
      there, no, but I do imagine all sorts of scenarios. In doing so, they&#39;ve had me accept all sorts of situations
      without being fully prepared to accept them. This has been going on for quite some time. It&#39;s as if someone
      who is experienced and older has taken all the pitfalls they&#39;ve experienced, wrote them down, and is acting
      upon them in my life as they are just putting me through situations I&#39;m just not even prepared to deal with.
      This was all done purposefully to get me to accept a way of life that just isn&#39;t normal to me. As if someone
      has a bet they are trying to make.
    </p>
    <h2 id="friends"><a href="#friends">Friends</a></h2>
    <p>
      Well, a lot of effort has been placed by myself to create a friendship with all the people I grew up with.
      I&#39;ve been without a vehicle most this time and it&#39;s just been one thing after another. For a good 10 years
      I just focused on my family and decided not to really hang in the same social circles as it all came apart. What a
      mistake I made trying to accept these people as friends. I should have known better that they aren&#39;t even real
      people they are some type of scammers who are constantly on the run.
    </p>
    <p>
      I previously mentioned Steve, and said how I was hanging with him, which it just wasn&#39;t true. I think he came
      over once or twice and we just talked outside but I honestly have not spent time with these people as they are
      just so bogus. Not one thing he says is true and I just don&#39;t like him. He has stolen from me, lied to me,
      recorded my conversations and send them to people we were talking about when he was just as guilty, just all the
      typical little brother type stuff that I&#39;m not even related to the kid. He&#39;s older than me and has more
      experience so he uses that to his advantage. I just realized what a piece of trash he is and how much of a
      criminal he is. I should have never been around him, but that&#39;s what happens when criminals are let loose to
      just run free.
    </p>
    <h2 id="ex-and-39-s"><a href="#ex-and-39-s">Ex&#39;s</a></h2>
    <p>
      I&#39;ve only had a couple ex&#39;s. Two to be exact. They were both longer than 2 years so long term
      relationships. I haven&#39;t dated much and I don&#39;t really like it. The thought of being with different people
      intimately like that is just off-putting and disgusting to me. These people act like they don&#39;t care and just
      share the intimate moments with everyone but then when it&#39;s all said and done they regret it and have
      reactions that definitely will let you know they do care, and they care deeply. That&#39;s what I am dealing with
      now, people see me as some type of innocent angel they can come gripe to and show me all the bad stuff they&#39;ve
      experienced. They usually get dealt with pretty harshly.
    </p>
    <p>
      I have no idea the status of my ex who I was with for over 10 years. The so called friends aren&#39;t helping, in
      fact, they are enjoying the negative effects its having on my life. It&#39;s funny because they are helping the
      ones that are hurting them, thinking its the opposite. I enjoy seeing someone like that get hurt. They deserve it
      and seeing them get whats coming is really rewarding. Once they are gone? The atmosphere changes for the better.
    </p>
    <p>
      I can&#39;t find anyone to help me get the information I need. I know that these are the same people who are
      responsible for the crimes that are being committed against me. They are trash people and have no friends because
      of how they treat everyone. I am a stupid person who thinks that by some miracle I would help change them for the
      better. It just is not true. These people do not change for the better and belong away from society by whatever
      means necessary.
    </p>
    <p>
      I need to know what the hell is going on. What kind of a person spends that amount of time with someone only to
      never talk to them again? That&#39;s pretty damn pathetic and unacceptable. Stuff was taken from me and I need
      answers. You can&#39;t treat someone like this it just isn&#39;t right. I am suspecting drugs are involved with
      them, as well as military and the criminal element.
    </p>
    <p>
      I would never have been intimately involved with someone I wasn&#39;t going to spend my life with and I&#39;ve
      said that over and over to her she knew that. It was a staple of our relationship because I wasn&#39;t trying to
      just mess around. Apparently she just wants to sample my time and then run off and steal from me aided by her
      fellow heroin addict &quot;friends&quot;. It&#39;s not right. I&#39;ve never given her drugs. We used to smoke
      weed, but I never would approve of doing hardcore drugs they are a waste of life. For this to happen is just wrong
      and its being perpetuated by drug addicts and just piece of trash people who enjoy the damage they are causing.
    </p>
    <h2 id="complaints"><a href="#complaints">Complaints</a></h2>
    <p>
      I can&#39;t even get a decent supply of hemp to start a business. I am being monitored and harassed. There is a
      crime ring here of heroin addicts and other drug users that have infiltrated every facet of every service
      available, which it&#39;s really no surprise being in a small town. They do all know each other and do all work
      together. They are aware of the relationships these people have and they do use it to their advantage all the
      time. In other words, they know and let this stuff happen. I&#39;m sick of it. I can&#39;t do anything here there
      is no opportunity. They will pretend to have some type of thing going but will tell you that you just aren&#39;t
      the right fit. It&#39;s like that with EVERYTHING there is no opportunity and when people try to provide one they
      quickly realize what a fool they are and what a pageantry it all is. That&#39;s the main gripe, that&#39;s why
      these things are falling so quickly like they do.
    </p>
    <p>
      These people here are straight failures. They&#39;ve ran their situations into the ground I can&#39;t even believe
      they are still alive they are so pathetic. Most of them are not. A lot of them simply perished due to stupidity.
      We can&#39;t save stupid people, its not in the cards. No matter how hard you try, if you save someone like that,
      you will always have to provide that lift for them. You can&#39;t grow someone&#39;s life for them. It just ends
      up being you trespassing your own growth in their life.
    </p>
    <h2 id="compliments"><a href="#compliments">Compliments</a></h2>
    <p>
      There have been many strides. I&#39;m taking my health seriously now and it&#39;s paying off. With the advancement
      of hemp products, I&#39;m really able to heal myself and take care of myself properly. The hemp products help me
      immensely. There are many other strides as well. I am advancing technologically, socially, and mentally. My health
      is improving.
    </p>
    <p>
      I found some blockage clearing in my ears. It smells like epoxy resin. It honestly seems like some epoxy resin was
      poured into my ears. I really hope this isn&#39;t the case. I hope that I wasn&#39;t poisoned by someone who was
      close to me. That would be upsetting to say the least.
    </p>
    <h2 id="end"><a href="#end">end</a></h2>
    <p>
      It&#39;s looking more and more like the person is on the run or hiding out instead of just not talking to me or
      whatever. This is not as much of a surprise as it is a let down. I would not have become involved with someone
      like that. I am all about kindness and justice not pouring some poison in someone&#39;s food and running away.
      Prostitution is not okay. I am so tired of seeing it and getting messaged by these trash. I am a decent person and
      I have never been involved with any of that stuff. I am not accepting it as a way of life, they claim this and
      that but its sick and all I hear is some crying by someone who is trying to make themselves feel like less of a
      piece of garbage.
    </p>
    <p>
      It&#39;s not okay to sell yourself and they act out when its over. The people who advocate they are going to end
      up dead before the consequences have a chance to hit them properly. They will have to deal with it in the
      afterlife if they even get to experience such a thing. They do care. All of them care. It&#39;s just absurd to
      think that someone isn&#39;t affected. Whether it has a bearing on their future actions is another story
      altogether.
    </p>
    <p>
      Well, if anyone out there has any info that can help me, I am not trying to contact these people or whatever kind
      of crazy scenario they are trying to have you believe. I have one intention and one intention only. That is to get
      the upper hand in this situation they&#39;ve gotten me in. They are attacking me, I have lost all my money trying
      to buy food that is not bad, trying to buy supplies to sell for my business that are not tainted. I have 0 funds
      available, there are no jobs or opportunities that are safe here. The jobs available are run by drug addicts,
      criminals, and they do not pay you. They will try to pay in drugs or other ways. There is all sorts of corruption
      and they are just using people as if they are toys violating their rights here like it&#39;s nothing making a
      sport of it with each other.
    </p>
    <p>
      If you have any information, just email me <a href="mailto:stephen730@protonmail.com">
        stephen730@protonmail.com
      </a>
      . Or you can text or call me,
      <a href="tel:17063159678">+1(706)315-9678</a>
      . Just leave a message I&#39;m rarely by the phone but I will return the call quickly.
    </p>
    <p>
      Not one single person is contacting me back and I have left this alone for 12 years since we split. Now that I am
      being stalked I need help identifying who else it is. I have left it alone for 12 years and now they are treating
      me as if I am a stalker something is definitely not right. So I am kicking down proverbial doors for the
      information and am prepared to do whatever it takes.
    </p>
    <p>
      I&#39;m not really sure what the heck I need to ask for to know what to do, I just know if I ignore this that
      these people will continue to attack me.
    </p>
    <Youtube id="ld-NN74o48I" />
  </article>
</Post>
