<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="next-sunday"><a href="#next-sunday">Next Sunday</a></h1>
    <p>
      I wrote this as a follow up to the current condition. Rarely do I linger on subject, I love to dance around them
      then bring them all together in the end. However, this time I have to follow up.
    </p>
    <p>
      So I&#39;m starting to feel a little better. There is some nerve damage and there is some cognitive function that
      I&#39;ve lost. That is for SURE. Now... how you may interpret this, how you may read this is not how everyone else
      will interpret and it&#39;s probably not even reality. There has been some question as to my emotional state while
      I am writing this stuff and I have to tell you, even though these words may burn like hellfire, I am calm and my
      writing is creative exercise. I was guaranteed freedom from persecution when expressing myself and I am prepared
      to fight for that right. Otherwise I wouldn&#39;t even express myself and you people have no right trespassing
      upon my private thoughts. So anyways....
    </p>
    <p>
      There is some nerve damage and 2 impact marks. One of the marks, there was originally three, impacted on the tip
      of my cheekbone and therefore did not penetrate fully. The two impact marks are clearly visible as such.
      That&#39;s where the source of it is. Now it&#39;s also happening when I clean out that shed so I think a
      combination of all of those things. Every time I clean out that house out back I get violently ill. Might be a
      vermin situation or something. I need to learn to wear full coverings when cleaning stuff. I usually just throw
      myself in the midst of jobs and just get to work figuring out everything as I go. I love to work and I love to
      take on crazy tasks that seem impossible and get them done in less than an hour type stuff.. I&#39;m getting older
      and cannot go as fast as I used to. It&#39;s really starting to show. Plus, I haven&#39;t really worked much in my
      adult life because of the lack of employment. I&#39;ve just done stuff around here to help my family. We&#39;ve
      come a long way from what this place used to be. It&#39;s still not 100 percent, but it&#39;s getting there.
    </p>
    <p>
      Well, I started listing things for sale. I had an eBay account and purchased a bunch of stuff to sell so I could
      get my ranking up. I figured that might be a smart idea. It was recently with the coronavirus that I had a
      security incident when I was sick trying to get someone to help me sell some stuff and it turned out that my
      account got terminated or put on hold, i can&#39;t get the ebay people to even talk with me properly about the
      situation. All I know is that it is impossible to get it back to normal without paying some type of fee for
      something that never took place. They are extorting me. Upon research it&#39;s quite common.
    </p>
    <p>
      These companies are all so terrible I&#39;d stay away from anyone who sells stuff without someone responsible
      within throwing distance. If you can&#39;t see anyone? There is a good chance it&#39;s because their products are
      dangerous and they are hiding from everyone.
    </p>
    <p>
      Well, I don&#39;t take drugs so we can rule that out. I haven&#39;t been overdoing it too, too much. I&#39;ve been
      eating a lot of meat so I stopped that again altogether. I can&#39;t even think about eating a meat without
      becoming ill. I&#39;m pretty sure it was a combination of everything plus probably some existing things. The
      anaphylaxis shocked my body into a better state and I am starting to notice a lot of healing going on that was
      previously thought to be impossible on my behalf. So that&#39;s super cool, I really want to get better I am
      working tirelessly to that objective, I&#39;d hate to go through life never experiencing it the way I was meant
      to.
    </p>
    <p>
      This town is full of idiots and just horrible people. Not one good person exists here. They are all just such
      trash that is for sure. It&#39;s unbelievable how awful everyone is and I am truly shocked. If I had known this
      then, well it would have been a different story that&#39;s for sure. So the rules are now I could care less about
      anyone from my past, I don&#39;t want to interact with you, stay the hell away and that&#39;s that. Everyone I
      knew was just such awful people. Most are in prison, dead, or just bad off. Stay away I want nothing to do with
      you people.
    </p>
    <p>
      That&#39;s what is so hilarious because people thought they would go and befriend my enemies and things would be
      all great but what they didn&#39;t understand was they just got ate up in the process. Smart moves. They thought
      it was a game but found out it wasn&#39;t. I don&#39;t even know why they made the decisions they did and what
      not. It was probably drugs come to think of it. Once the drugs wear off and they&#39;ve used you all up? Well
      that&#39;s about the time they try to come crawling around.
    </p>
    <p>
      Pathetic. That&#39;s why I just want nothing to do with these scum. At first I give people the benefit of the
      doubt. They&#39;ve obviously failed in whatever task they&#39;ve promised.
    </p>
    <p>
      I always tried to offer to start a business or at least lets come together to do some work with computers or
      technology or something. Time and time again I was shrugged off as just a stupid guy trying to work for a living.
      These are not your upstanding citizens, these town people are all drug addicts. You&#39;d be surprised just how
      many here are a waste.
    </p>
    <p>
      The way they band together and attack anyone who resembles freedom. They will tell you how it is, how it&#39;s
      going to be and will oppress you until you are forced to live like they are. If you show any sign of difference to
      it? They attack it as someone else and will relentlessly pursue you and persecute you. No matter what you do, they
      will find fault with the air you breath and find a way to blame it on you. These people cling together usually
      because they&#39;ve committed a heinous act together.
    </p>
    <p>
      This is not a place full of opportunity, happiness, or lightheartedness. These people are all monsters using there
      facades to ensnare more and more victims.
    </p>
    <p>
      I&#39;m stuck helping my mother. I can&#39;t leave her here like this, she&#39;s the only person that helped me
      out all these years. This place is a nightmare and she keeps getting ripped off by service people. Recently
      we&#39;ve had a good run these past few years but before that was a nightmare. I handle all the repairs here
      myself. That&#39;s one thing she hasn&#39;t had to hassle with or pay for, is a good repair technician. Lately the
      house stuff has just become too out of hand we&#39;ve had to hire outside help in certain areas.
    </p>
    <p>
      This town is full of criminals. They won&#39;t deny it. Keep that in mind when judging me and my actions. I
      can&#39;t find decent work cause I refuse to be a criminal or sell drugs. That&#39;s where 100 percent of my
      problems are. I&#39;m targeted by a gang because they got everyone doign heroin and I flat out refuse to do that
      stuff. I got good information about all kinds of interstate crimes, all kinds of foreign influence type stuff,
      names, dates, etc. No one has EVER contacted me despite me filing FBI reports. So all that law enforcement stuff
      is just one big lie. Think about it, even their own law enforcement doesn&#39;t believe in the system. It all
      boils down to grown men trying to play god. That&#39;s it. Simple as that.
    </p>
    <p>
      I&#39;m not complaining, I&#39;m fed up and I am expressing myself. I&#39;d tell you what I&#39;d like to do
      instead but I&#39;d probably get in trouble. Heh.
    </p>
    <Youtube id="PiBX-ESFDF0" />
  </article>
</Post>
