<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 888;

  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h2 id="facebook-rumors"><a href="#facebook-rumors">FACEBOOK RUMORS</a></h2>
    <p>
      Let&#39;s just go ahead and address the Facebook rumor upfront. I was just recently made aware that this may be
      related to me not just a coincidence and upon further examination, it most certainly is a hoax. I do not own a
      Facebook page, the one that is up there is an annoyance, its crude and disgusting, its computer generated, and its
      sick. They call it A.I. but there is nothing <em>intelligent</em>
       about this.
    </p>
    <p>
      If you scroll down past all the atrocious stuff you can see the original mk.1 release of the ai software designed
      to illicit and provoke a primal response or so the author believes. The page is also one of the only ones that
      have a public viewing container which allows it to bypass all the search engine rankings by becoming a page 1 rank
      due to all the backlinks from brand loyalty. They now just drop the restrictions upon names which they are able to
      harass remotely. This is also the case with twitter, zocdoc profiles, linkedin, and many of the other spam sites
      that have remained persistent over the years. They are indeed one in the same. Major conglomerates you have to log
      in to be able to view, why does this one person who is obviously not a serious individual but an actor or a name
      it would seem, have a publicly viewable profile without having to log in? Main purpose is harassment.
    </p>
    <p>
      To make it quite clear, no that is not me nor have I ever had a facial beard like that nor do I resemble that
      character. I have an extremely serious tone compared to these other jokers. However, if you examine my motives and
      work it is also more lighthearted then these other jokers. They used this stuff to call me racial slurs when I was
      playing online games, they&#39;ve made threats and all kinds of stuff. I have filed NUMEROUS reports and nothing,
      no response, no follow-up, nothing. They led me to believe it may be someone so I made an anonymous GBI report and
      they just alerted the local law enforcement like it was a light show. So I have abandoned any effort to involve
      any official capacity moron that may be lurking out there. This is the main reason why I am posting my information
      so freely upon the internet because I believe in transparency. To a degree, I must add.
    </p>
    <h2 id="i-and-39-ve-come-under-fire-all-my-life">
      <a href="#i-and-39-ve-come-under-fire-all-my-life">I&#39;ve come under fire all my life</a>
    </h2>
    <p>
      I&#39;m no stranger to any of this war stuff, this supply line tussling, or any of this conflict type situations.
      In fact, I&#39;m quite adept at handling it. The only issue I have is when people misrepresent the situation as
      peaceful. Simply put, it&#39;s not. This is why it is so important to teach the younger generation responsibility.
      Not only teach them, but remind ourselves as well. Things have to be done a certain way, life has to be respected.
      The ones that fail to do so, fall easy.
    </p>
    <p>
      The last thing I want to be doing is talking about my problems. However, the situation demands I do so. Usually
      when I am vocal about some types of plans, as usual, there is always someone to try to topple whatever I&#39;m
      trying to build. For whatever reason, they are always going to be there whether they want to be or not. They will
      often try to rationalize it with the, &quot;WHAT WAS I THINKING?&quot; response. But this is just a cover for the
      truth. They lack the willpower to act upon their own accord. But you have to talk about it because it&#39;s of no
      fault of your own. Even though it may appear so? It never ends up being that way.
    </p>
    <p>
      People like to take shots and then go around telling other people and when they are smart enough to avoid that
      person, they misjudge that response as something to be won or a trophy of some sort. Very rarely are these same
      people able to create anything of their own that&#39;s worth while. It&#39;s not even about the quality or what
      would be considered valuable, its more about being free in mind and being able to create. One doesn&#39;t try to
      compete at this level either. They simply appreciate their fellow man, eternally striving for perfection. It&#39;s
      not something to be won, it&#39;s just the byproduct of the process.
    </p>
    <p>
      It&#39;s hard to properly relate such concepts to everyone as I would have to have a footing to be able to portray
      said concepts. But it does exist, universal information does exist and the transfer is there. The realization may
      come later, but it&#39;s still there.
    </p>
    <p>
      They rely on your embarrassment to keep quiet. I see results but they are natural results. They aren&#39;t brought
      on by any one person&#39;s actions. We keep cool about stuff, but when its detrimental to everyone and beneficial
      to no one? It makes no sense to protect some stuff like that.
    </p>
    <p>
      So many times I&#39;ve relied on others to confirm my suspicions so as I may act accordingly and thankfully
      they&#39;ve always been there when I need them. So much so I am able to fly on my own now.
    </p>
    <h2 id="bluesky"><a href="#bluesky">BLUESKY</a></h2>
    <p>
      Okay okay okay, bluesky. It&#39;s decentralized, peer-to-peer communications. I&#39;ve got my domain linked into
      it, you can find me <a href="https://bsky.app/profile/fediverse.stephenlittleton.com" rel="external">
        @fediverse.stephenlittleton.com
      </a>
       there. I&#39;m focused upon things that are going to be positive. The rest of it can get lost.
    </p>
    <p>
      So far bluesky is pretty cool, it is just like twitter but with some obvious improvements. You can&#39;t pull the
      same stunts you pulled at twitter with the ascii text art. They fixed the breaking line stuff pretty quickly. The
      ambiance is nice, its classic but modern. Okay, okay... its pretty futuristic scifi and I&#39;m happy as hell I
      found out they were accepting people without invites. I need to be apprised of this stuff and have some real
      experience. I&#39;ve just been involved with proof of concept and now it&#39;s actually coming true. Quite an
      experience and it&#39;s free and edge. So one can understand why I&#39;m so.. elated.
    </p>
    <h3 id="links"><a href="#links">Links</a></h3>
    <p>
      <a href="https://bsky.app/profile/fediverse.stephenlittleton.com" rel="external">
        My Bluesky Social Network Link
      </a>
      is here,
      <a href="https://bsky.app" rel="external">bsky.app</a>
      , in case you want to check it out. Notice the .app extension that is so popular among projects these days. You
      can also access it at
      <a href="https://blueskyweb.org" rel="external">BlueSkyWeb.org</a>
      .
    </p>
    <p>
      I&#39;m not too sure about the mobile app as I have not attempted it. I am just now figuring out the AT protocol.
      I&#39;m a big fan of XMPP protocol, the old jabber, mIRC and whatnot.
    </p>
    <p>
      Be sure to check out the <a href="https://stephenlittleton.com/about/" rel="external">ABOUT</a>
       page here for more of my work, my music vids site is there, my directory, nexflix, and more is there. It&#39;s at
      the top of the page under the drop down on mobile and some versions of pc, or directly located at the top to the right
      of the LOGBOOK logo. That&#39;s where I will store most pertinent information on how to contact me or what is the main
      purpose or intentions of the site.
    </p>
    <p>Til&#39; next time.</p>
    <Youtube id="srSL_mViLb0" />
  </article>
</Post>
