<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;

  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h2 id="enemies"><a href="#enemies">Enemies</a></h2>
    <p>
      We all have our enemies. Some of us do not, but we are not talking about them because they exist in places other
      than the here and now. Everyone of us is in conflict and fighting for survival. Unknowingly to us, there are those
      out there who firmly believe this and so make it into reality. As much as we&#39;d like to believe there is an
      invisible force holding us back and fighting us, there simply is not. When setting out to do certain things with
      certain intentions you are simply met with the resistance that is normally there for everyone. This time, for me,
      it just so happened to appear in the form of a local crime ring amongst many other places. There are those that
      oppose and there are those that oppose by force. Deciphering what enemies are what takes some doing. That
      information can be ascertained easier if you take a temporary stance when you try to catagorize them. Once again,
      this is only a temporary stance one should take. Everyone is a unique and worthy of their own respect these are
      just the positions we take when dealing with only a part of them. No person should be solely judged by one thought
      or action except those devestating actions which deserve such a response. For instance, murder should be judged by
      that one incident and so should other crimes which cross the line as it were.
    </p>
    <p>
      My enemies are those that want to have special memberships where certain people are excluded from experiences we
      should all get to be a part of. I really do believe in fair &amp; equal opportunity for all. I appreciate
      everyone&#39;s differences with the proper respect it deserves. I do not discriminate and in the real world, that
      is a tall task. There is such a drive to team up and flock together to create some type of invisible skeleton man.
      It&#39;s not healthy. It was created during the 1980s and we all know the motives behind that era. I do not think
      people should be enslaved and worked over like some kind of nutter farm animals. That&#39;s the best they can
      manage because we aren&#39;t really good at anything other than simply existing and observing. Money, Food, Light,
      Water, Oxygen, even our very own DNA and our bodies have to be provided for us. As information, we are simply
      unable to create these things on our own and we would not want to. That would be a self sustaining environment and
      we just wouldn&#39;t grow nor would we survive. Entropy would set in faster than we would be able to process it.
      There must be that outside spark to get things going. This is why we have enemies, this is why we have allies.
    </p>
    <p>
      In our quest to find supplies, decent communication lines, social enviroments, we often run into others who have
      the same motivations in mind. This can create friendships and this can also create enemies. Percieved limitations
      upon supplies can cause competition in purchasing which can lead to oversupply. There are all types of
      consequenses one may face when choosing to deal with the outside world. More so often than not, however, there are
      great rewards. Especially in America! There are so many people here who are just interested in doing a good deal
      and making the right thing happen. It&#39;s so easy to stand firm in your convictions once you realize this. Not
      only that, but the number of people willing to do things right far outweighs those who just percieve the world as
      falling apart with no hope.
    </p>
    <p>
      I don&#39;t neccesarily go out to defeat my enemies, it just happens. I take a firm stance and they just can&#39;t
      even survive next to me. So that&#39;s it. It ends it right there. We are not out to defeat enemies and prevent
      them from becoming allies, no. We are quite the opposite, we pursue avenues which the enemy becomes the ally. We
      are all in this together and we must survive. There are very few things which can prevent an enemy from becoming
      an ally but they are there. While an ally may never truly be accepted as a close friend, they are still people we
      work with and still are there to lend a helping hand as far as the greater good goes. The higher purpose that is
      what we are fighting for. Allies are those who we see are fighting beside us.
    </p>
    <p>
      We just hope you are not a bad person to end up as the enemy. There is a much greater future ahead for those of us
      who are friendly. America is such a great place when we all are getting along.
    </p>
    <Youtube id="7LnBvuzjpr4" />
  </article>
</Post>
