<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;

  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h1 id="becoming-a-full-stack-web-developer">
      <a href="#becoming-a-full-stack-web-developer">Becoming a Full-stack Web Developer</a>
    </h1>
    <p>
      Being a real full-stack web developer isn&#39;t that far away. I&#39;m just not so familiar with JavaScript as
      I&#39;d like to be in order to say I&#39;m well versed in it. I just don&#39;t really know where to start.
      I&#39;ve never had a need to get into it so I&#39;ll have to do that all on my own.
    </p>
    <h2 id="what-is-a-full-stack-web-developer">
      <a href="#what-is-a-full-stack-web-developer">What is a Full-Stack Web Developer?</a>
    </h2>
    <p>A full-stack web developer is someone who programs both client and server software.</p>
    <p>
      Technically I can call myself a full-stack developer, but, a full-stack web developer is a bit more complex. I
      would have to be a bit more proficient in JavaScript and specifically the browser programming side as I&#39;ve
      really had little to no experience with browser programming.
    </p>
    <p>
      I&#39;m a repair technician and I fix anything that can be fixed. I enjoy the challenge, it comes naturally and I
      never YouTube stuff unless I&#39;m just stuck. I didn&#39;t learn my trade by watching how to videos, I learned my
      trade at the same time, showing others how to. It was always a necessity when you are impoverished.
    </p>
    <h1 id="the-advantages-and-disadvantages-of-full-stack-development">
      <a href="#the-advantages-and-disadvantages-of-full-stack-development">
        The Advantages and Disadvantages of Full-Stack Development
      </a>
    </h1>
    <h2 id="advantages"><a href="#advantages">Advantages</a></h2>
    <p>The advantage of being a full-stack web developer is:</p>
    <ul>
      <li>You can master all the techniques involved in a development project</li>
      <li>You can make a prototype very rapidly</li>
      <li>You can provide help to all the team members</li>
      <li>You can reduce the cost of the project</li>
      <li>You can reduce the time used for team communication</li>
      <li>You can switch between front- and back-end development based on requirements</li>
      <li>You can better understand all aspects of new and upcoming technologies</li>
    </ul>
    <h2 id="disadvantages"><a href="#disadvantages">Disadvantages</a></h2>
    <ul>
      <li>The solution chosen can be wrong for the project</li>
      <li>The solution chosen can be dependent on developer skills</li>
      <li>The solution can generate a key person risk</li>
      <li>Being a full stack developer is increasingly complex</li>
    </ul>
    <h1 id="examples-of-popular-stacks"><a href="#examples-of-popular-stacks">Examples of Popular Stacks</a></h1>
    <p>Some examples of popular stacks are:</p>
    <ul>
      <li>LAMP stack: JavaScript - Linux - Apache - MySQL - PHP</li>
      <li>LEMP stack: JavaScript - Linux - Nginx - MySQL - PHP</li>
      <li>MEAN stack: JavaScript - MongoDB - Express - AngularJS - Node.js</li>
      <li>Django stack: JavaScript - Python - Django - MySQL</li>
      <li>Ruby on Rails: JavaScript - Ruby - SQLite - Rails</li>
    </ul>
    <p>
      I can pretty much claim LAMP and Ruby on Rails but the latter I&#39;d have to have a bit more real world
      experience before I&#39;d feel comfortable claiming it fully. I&#39;ve had little experience with a lot of the
      newer ones and the more advanced stuff, but I&#39;ve seen a lot of documentation and been part of a lot of chats
      and had to work around it so I&#39;d pick it up almost instantly.
    </p>
    <p>
      My turnaround time is a day. I can learn this stuff in little to no time. The only real issues are my living
      situation and that just requires a few paychecks to set in the right direction. That&#39;s it, I have no ties or
      any kind of strings that would attach me to anything, anywhere, period. So that makes me free to choose really
      anything I want that is available to be chosen. I&#39;d like to move somewhere more sunny and set up shop.
    </p>
    <p>
      I was thinking about moving to somewhere nice and opening a development studio both for graphics and webapps. I
      would like to do a school and help everyone create teams and get started.
    </p>
    <p>
      One thing that persists, the medium upon which everything is distributed. The format, the underlying technology,
      these can be just as wonderful as the media they display. The movies themselves are only one part of the
      magnificent experience. The music is heard clearer and the experience becomes much more personal. This is thanks
      to the medium upon which it is transferred and the underlying technology upon which it is served from.
    </p>
    <p>
      So hopefully once my commitments here are completed I&#39;ll have a clear plan of action and just need to stick to
      the plan, as easy as that may (or may not) be...
    </p>
    <Youtube id="7eH_q4U0dbQ" />
  </article>
</Post>
