<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
</script>

<Post>
  <article slot="post_content">
    <ImgZoom src="/snark/Northrop_SM-62_Snark_061218-F-1234P-006.jpeg" alt="Snark Missle" class="h-full object-cover">
      A photo sequence showing the warhead's separation sequence
    </ImgZoom>

    <ImgZoom
      src="/snark/Northrop_SM-62_Snark_061218-F-1234P-002.jpg"
      alt="Snark Missle Nose Up"
      class="h-full object-cover">
      Aerial photo showing the Snark's nose-up attitude in flight
    </ImgZoom>

    <Youtube id="8efXm3ijSNA" />
  </article>
</Post>
