<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;

  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h2 id="stupidity"><a href="#stupidity">Stupidity</a></h2>
    <p>
      Well, in all this madness going on lately, I had actually put a lot of bad experiences with my previous life in my
      past behind me for 12 years now and had moved on. So when they pulled this little stunt here, I had forgotten how
      horribly I had been treated and all the bad stuff came back to me. I felt kind of stupid after remembering how
      poorly I had been treated and not only that but it got me thinking on to how she treated everyone else in her life
      and that is also something else to be astounded at. We all say things we don&#39;t mean, I&#39;m guilty of it for
      sure. People know this, they just use it as an excuse sometimes to do justify the awful things they do.
    </p>
    <p>
      These people are actually just sick with a mental disease. They are in love with a concept in their mind they had
      when first browsing a social media and imagined a world out there with all these happy brightly colored people.
      It&#39;s just not the case. They can pretend all they want, but if you have to force it, or make it happen? Then
      it&#39;s not true. They claim not to care. When it is all over, their actions speak differently and the ones who
      try to help them are the ones who end up getting hurt. They dehumanize people and replace them with their ideals.
      That&#39;s why they feel such a need to control what you do, because they are wanting to be with an ideal.
    </p>
    <p>
      I feel kind of stupid about it. In life I went through thinking everyone was deserving of the same respect I
      receive. I find that now to be the stupidest thing I could have thought. Through no fault of my own, I tried to
      help everyone thinking that they would return the favor. It&#39;s just not true. They really do deserve to be
      struck sometimes and it&#39;s just not as great as they make it out to be, however, we still have to follow those
      guidelines if we want a productive canonical lifestyle.
    </p>
    <p>
      I&#39;ve decided to just get my anger out, I know I probably seem pretty tame and goofy with my insults and
      retorts but whatever, I don&#39;t usually sit around trying to destroy people, I sit around trying to make a joke.
      So if it&#39;s more funny than anything now you know why. I feel run down and depleted when arguing like that with
      people especially when they don&#39;t realize how crazy they are looking. It has to be confronted sometimes,
      especially now, for me because I&#39;m tired of it, period.
    </p>
    <p><ImgZoom src="/stupidity/RHVNNEN.jpg" alt="Back to the Future DeLorean"></ImgZoom></p>
    <h2 id="turned-around"><a href="#turned-around">Turned Around</a></h2>
    <p>
      I got mixed up and turned around. I&#39;m starting to realize I&#39;m the victim of a crime ring and there is some
      real serious stuff going on. No more than usual, but it&#39;s there. I tried to start a business but all my
      supplies got trashed and the businesses refused to refund or make things right. It was like I was being boycotted
      and I&#39;m just a regular person. I didn&#39;t even have a social media at the time. I had this feeling like
      there was a man in the middle attack going on. I lost almost everything and I couldn&#39;t even get food that was
      normal, everything was messed up and I had to use my credit cards to order from places that one wouldn&#39;t
      normally think to order from. I also found that this delta and CBD stuff worked wonders for whatever that illness
      I had when the covid-19 was going around. Might have been coronavirus. Either way, it helped so much but they kept
      sending me stuff that wasn&#39;t delta or CBD. It was like liquids. When taking it, it made me dizzy so I just
      threw it into a large clear bag. At the end of the experience? I had so much tainted product in this garbage bag
      full of stuff that was supposed to be items that were for my health.
    </p>
    <p>
      They are intentionally keeping me sick. This is done to discredit me and make me look weak and feeble. Then they
      treat other people like they are the good ones and they pitch the two sides against each other just like
      they&#39;ve always done in their own lives. I can tell it&#39;s certain people and what is going on because they
      are having others do the job for them. It&#39;s not the same and the whole thing is just another way for them to
      inject themselves into people&#39;s lives where they are definitely not wanted.
    </p>
    <p>
      That is the issues that they claim not to care about, but then they turn around and do all sorts of crazy stuff.
    </p>
    <p><ImgZoom src="/stupidity/MTM3NjEyNzY4MzgyNTU5NDc0.jpg" alt="Highway at Night"></ImgZoom></p>
    <h2 id="a-return-to-exploration"><a href="#a-return-to-exploration">A Return to Exploration</a></h2>
    <p>
      So, I&#39;m back to exploring again. I&#39;ve done a lot of it and it&#39;s so much fun. I have a lot on the
      agenda, I would like to start to learn Javascript but I want someone to teach me. I want to develop a friendship
      with that being the driving force. Maybe not so much a friendship as an acquaintance but whatever the relationship
      may be, I would like to learn Javascript in a social setting with someone who knows a lot about it and has the
      experience to teach me properly. I think that would be fun. I just don&#39;t have it in me anymore to take on
      something like that alone because its getting to be too much I have to do anyways. It just makes sense to me to do
      it that way.
    </p>
    <p>
      For the first time since it&#39;s invention I actually went through Facebook and looked at it like it was supposed
      to be. I was curious as to who the hell these people are, why did they look like they did, and where the heck they
      came from. So I started exploring. I found that they are mostly fake. I never really clicked them before, I just
      looked at it and was like that&#39;s weird, and moved on. So I explored and saw what people are posting and how
      all this ties in. It creates this fake sense of what&#39;s out there. Everyone tries to force this ideal and
      it&#39;s just not working so far. Then they take substances thinking that will correct everything and you end up
      getting some weird drag stuff. When it&#39;s over? It&#39;s over. There were some great times, party people were
      everywhere. But, we all need to rest. Some of us just don&#39;t seem to understand that the lifestyle ends after a
      few. Nothing lasts forever. All these people who are claiming to be so unique just want everyone else to be like
      them. It&#39;s crazy and it&#39;s sad, get over it and move on so we can live our lives.
    </p>
    <p>
      There is a lot of progression in the area of moving on, I&#39;ve noticed. Things are improving, things are looking
      much better. We can&#39;t claim to be part of the solution without ever even trying and that&#39;s what a lot of
      people have been doing. Just giving it their all and really making a difference. I know it feels that no one sees
      it, but really, everyone sees it, it&#39;s true. Just because we don&#39;t feel like we are being noticed,
      doesn&#39;t mean we aren&#39;t being noticed. I went through feeling like I am in a black hole but that&#39;s just
      all in my head.
    </p>
    <p>
      <ImgZoom
        src="/stupidity/IMG_147711.jpg"
        alt="A ship skirting the clouds on a planet with an earth like planet seen off in the distance"></ImgZoom>
    </p>
    <h2 id="ai-stuff"><a href="#ai-stuff">AI Stuff</a></h2>
    <p>
      So much AI Stuff. When I say that, I am not talking about META and their obtuse view of what AI should be. Those
      are all cartoon stereotypes they&#39;ve defined. Real AI is everywhere. The way it all adds up? How everything
      seems like the world is talking to you? That&#39;s an AI. It&#39;s the arms and legs of our combined willpower
      powered by the laws, definitions, and bounds of our universe.
    </p>
    <p>
      They tricked me with all this. I thought these people were real and there was people like that out there.
      That&#39;s mostly why I became so upset but it turns out these are just things they do designed to trick you
      specifically crafted with years and millions of users worth of experience. It turns out they aren&#39;t it&#39;s
      just a select few people with mental disease that are up to this stuff. They then pass the buck to someone to take
      the fall. A fall-guy if you will.
    </p>
    <p>
      I know a lot of people just gave up and left to join these people to find out they don&#39;t even exist and I hate
      to admit this, but I find that mildly satisfying. I would never do that kind of thing to someone. I don&#39;t give
      up on people, I don&#39;t leave. I&#39;ll leave you alone if you want, but if you want a friend, I&#39;m there,
      always.
    </p>
    <p>
      These AI know no bounds. It&#39;s making me physically sick to see this AI stuff. There are those who just sit
      there all day who eat this kind of thing up but I can&#39;t stand it. I am all about the real life, reality.
      It&#39;s fun to do the AI but to worship it? No thanks.
    </p>
    <p>
      <ImgZoom
        src="/stupidity/i-should-buy-a-boat.jpg"
        alt="A generated image of what would appear to be a dock at night with blurred lights"></ImgZoom>
    </p>
    <h2 id="closing"><a href="#closing">Closing</a></h2>
    <p>
      In closing, I really need to know some answers as to the whereabouts and becomings of these people who were in my
      life and just disappeared suddenly. I know a lot of them perished. I haven&#39;t heard or seen anyone for a very
      long time except for one person, my friend Steve, and even him I have not seen in a long time. He was getting his
      Employee of the month on and really looked like he was living his life last time I checked. I&#39;ve been busy
      myself trying to recover from these illness and all these hits I keep taking. Once I found out that the other
      people who I used to hang with regularly were up to what they were all up to? I had to stop associating with them.
      I&#39;m just not like that I&#39;d rather be dead than do some stuff like that.
    </p>
    <p>
      I know they want me to be someone that I&#39;m just not. I&#39;m sorry but you have to look elsewhere for your
      catch of the day cause I&#39;m just a regular guy barely making it trying to make a better life. That&#39;s
      especially pertinent to the thieves and the crooked cops who think that because I have intelligence that I am the
      kingpin. Let me tell them something, those brain dead morons, intelligent people create the society we live in,
      they don&#39;t turn to crime, point blank.
    </p>
    <p>
      None of that movie stuff or tv show crime serial killer stuff is real. It exists only in the mind. The only time
      it is actually real is when they emulate it so that really doesn&#39;t count. But that stuff just doesn&#39;t
      happen. Most of the time, people get what they deserve and they are just good at getting away with it. Of course
      you have your exceptions but I guarantee if you look closely you&#39;ll discover there is more to the story.
      It&#39;s more of a war without uniforms type of situation.
    </p>
    <Youtube id="YpOYvsoFNkI" />
  </article>
</Post>
