<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;
  import Folder from '$lib/components/folder.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="putting-the-fun-back-in-functional">
      <a href="#putting-the-fun-back-in-functional">Putting the FUN Back in Functional</a>
    </h1>
    <p>
      Computers don&#39;t have to be lame, they don&#39;t have to be advertisement delivery machines. To me, the
      computer is the most powerful media tool. It can create amazing websites and with my help those sites can make
      sense. Most people use the computer simply because they have to or because they enjoy doing menial tasks that have
      nothing to do with it&#39;s intended purpose.
    </p>
    <p>
      Today, I will be diving into some must have&#39;s for the Windows PC. I usually develop Linux software and have
      not used Windows in over a year. We will be getting into the politics, the procedures, the standards, and the
      inner workings of what goes on within the Windows Operating system.
    </p>
    <p>
      <ImgZoom
        src="/functional/Minimalistic_texts_ships_pirates_the_pirate_bay_weapons_piracy_captain_swedish_boats_bay_weapon_of_mass_distribution_1920x1080.jpg"
        class="h-full object-cover"></ImgZoom>
    </p>
    <InfoBox statusType="info" statusName="General Disclaimer">
      <p>
        All of this pertains to Windows ver. 10 at this time. It should translate to Windows 11 just fine and still be
        applicable. All information is of my own opinion. I am not affiliated with Microsoft, nor do I work for them in
        any professional capacity.
      </p>
    </InfoBox>
    <h1 id="a-lighter-tone"><a href="#a-lighter-tone">A lighter tone</a></h1>
    <p>
      I&#39;ve been wanting to handle some tech blogs. I keep waiting for a good moment but it never comes. Today, I am
      just diving in. I recently installed MICROSOFT WINDOWS 10 and the process gave me the idea to write this blog.
    </p>
    <h2 id="essential-software"><a href="#essential-software">Essential Software</a></h2>
    <p>
      <strong>Essential Software</strong>
       to me indicates software that is always installed every single time as well as used every single time you install
      an operating system. When I install a computer fresh, it has all these softwares plus libraries and much much more
      installed. These are not just trial versions of the latest affiliate marketing programs, no sir/ma&#39;am, these are
      free to use, well developed pieces of art that you are lucky enough to have on your computer. It is the main reason
      my systems run as well as they do, are stable as they are, and last as long as they do.
    </p>
    <p>
      While I am available for hire, I&#39;ve decided to post a free version of my services so someone may do them
      theirselves. I am always available to go over the computer and get it going like we have listed in any of the
      examples. I can also do custom requests with no issues.
    </p>
    <p><ImgZoom src="/functional/pexels-alexander-dummer-132700.jpg" class="h-full object-cover"></ImgZoom></p>
    <h3 id="list-of-software"><a href="#list-of-software">📑 List of Software</a></h3>
    <ul>
      <li>
        <input type="checkbox" />
        IZArc or 7zip
      </li>
      <li>
        <input type="checkbox" />
        Surfshark VPN
      </li>
      <li>
        <input type="checkbox" />
        IO Bit Advanced System Care
      </li>
      <li>
        <input type="checkbox" />
        deadbeef audio player
      </li>
      <li>
        <input type="checkbox" />
        Firefox Web Browser
      </li>
      <li>
        <input type="checkbox" />
        Chrome Web Browser
      </li>
    </ul>
    <p>
      Now, IO Bit did not pay me, but I left a review and they asked for a picture on their free version, which works
      really well, and they sent me a free key which upgraded me to the paid version if they get to use my testimonial
      and my image. I agreed! It was kismet! It&#39;s already a good product and thats just fine by me. <a
        href="https://ru.iobit.com/recommend/ascfree.php">
        You can view me here.
      </a>
       You can also search my name on bing and click images and see the other pages I&#39;m featured at.
    </p>
    <p><ImgZoom src="/functional/pexels-markus-spiske-177598.jpg" class="h-full object-cover"></ImgZoom></p>
    <h2 id="operating-system-os-comparism">
      <a href="#operating-system-os-comparism">Operating System (OS) Comparism</a>
    </h2>
    <h3 id="pros"><a href="#pros">Pros</a></h3>
    <table>
      <thead>
        <tr>
          <th class="text-left">Linux OS</th>
          <th class="text-center">Windows OS</th>
          <th class="text-right">Apple&#39;s OS</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="text-left">Security</td>
          <td class="text-center">Games</td>
          <td class="text-right">Graphics</td>
        </tr>
        <tr>
          <td class="text-left">Privacy</td>
          <td class="text-center">Compatibility</td>
          <td class="text-right">Multimedia</td>
        </tr>
        <tr>
          <td class="text-left">Control</td>
          <td class="text-center">Ease of Use</td>
          <td class="text-right">Different</td>
        </tr>
      </tbody>
    </table>
    <h3 id="cons"><a href="#cons">Cons</a></h3>
    <table>
      <thead>
        <tr>
          <th class="text-left">Linux OS</th>
          <th class="text-center">Windows OS</th>
          <th class="text-right">Apple&#39;s OS</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="text-left">Hard to use</td>
          <td class="text-center">Insecure</td>
          <td class="text-right">Lack of stuff</td>
        </tr>
        <tr>
          <td class="text-left">Easy to break</td>
          <td class="text-center">Adverts</td>
          <td class="text-right">Not easy to use</td>
        </tr>
        <tr>
          <td class="text-left">High Maintenance</td>
          <td class="text-center">Tracking</td>
          <td class="text-right">Black Sheep</td>
        </tr>
      </tbody>
    </table>
    <p>
      Windows is great for gamers, students, and just everyone. It has all the features but they track EVERY SINGLE MOVE
      YOU MAKE.......... everything, from you clicking on the icon is tracked and sent back to microsoft. There is so so
      so so much to do to stop this its virtually impossible for any sane person to keep up with. Once you do
      succesfully block these people from tracking you they just find a new way.
    </p>
    <p>
      Linux is just wonderful for everyone. There is no time like the present to start learning how to use a computer
      and it just provides a wonderment of activities for everyone to participate in. There are so many and they are
      free. The good ones don&#39;t track you but they are all different versions of the same thing. Even android phones
      run linux. Windows even runs linux as an option. It&#39;s just hard to use. You don&#39;t get virus, or malware as
      much as you get targeted hacks.
    </p>
    <p>
      Apple is a beast of an operating system that defines proprietary. It will not let you do much and you are boxed
      in, but it&#39;s a really nice box. They are somewhat of a black sheep in the computer community so don&#39;t
      expect respect from learning the MAC and how it works. It&#39;s based off of UNIX subsystem. A commercial and
      proprierty operating system.
    </p>
    <h2 id="youtube-video-closing"><a href="#youtube-video-closing">Youtube Video Closing</a></h2>
    <Youtube id="teNvl4q43TM" />

    <h2 id="end"><a href="#end">👍 END</a></h2>
  </article>
</Post>
