<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;

  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h2 id="futuristic"><a href="#futuristic">Futuristic</a></h2>
    <p>
      So in all my efforts to pioneer a better tomorrow, I have been learning about all this other stuff and it&#39;s
      not so easy when you don&#39;t have the support you need to venture out into the world. Some of this stuff, it was
      like being told you are the first ones into space and seeing the arrival platform all graffiti&#39;d up. You just
      know there is some trouble ahead that they aren&#39;t even going to bother to tell you about.
    </p>
    <p>
      It&#39;s pretty pathetic when the price of the McDonald&#39;s meals are making the news headlines. Even worse? The
      fact that it doesn&#39;t matter to me because it&#39;s already become the first on the list of designated places
      that you just don&#39;t go. It&#39;s like that with a lot of the old candy, sodas, and other food products. They
      are just riddled with quality issues that will kill you. I just got an airheads bag that had like, bone in it. If
      you chew it, it will bust your teeth if you aren&#39;t careful. They make you sick as well. It&#39;s not the first
      time there have been many recalls. These products just buy their integrity from the brand names. The actual
      product varies and has nothing to do with the brand other than in name alone. Quality is less than desirable as
      its harmful and its just really been an eye opener.
    </p>
    <p>
      I used to wonder why these things did not happen when I was coming up. I suppose they did, you are just resilient
      when you are younger I suppose. The food products are whats doing it and it is surprising that more people
      aren&#39;t catching it. I think it&#39;s because a lot of people are taking substances they shouldn&#39;t and that
      is probably numbing the negative effects.
    </p>
    <h2 id="issues"><a href="#issues">Issues</a></h2>
    <p>
      I was recently looking for some answers and I have yet to find them. A lot of people claim to be my friend.
      Listen, I have had no friends come over on my birthday for like 20 years so these people are just people I knew. I
      spend my time mostly alone. I&#39;ve not been with many females, and I intend to save myself for the perfect
      situation I&#39;d hate to ruin my life for some 20 seconds of nothing. I just want nothing to do with that kind of
      stuff and those people. I&#39;m not looking for any kind of weird situation or anything like that, thanks. I
      don&#39;t know and I don&#39;t care who it is who is trying to flirt around with me, but they are unwanted. If
      anyone wants to contact me, straight up like an email, call, text or something face to face like that. I don&#39;t
      go for this other stuff they are trying to do. It&#39;s just not my style.
    </p>
    <p>
      I know that I am involved in a lot of social circles, but just barely as a name. That is mostly true. I would
      often just come by and we would give rides and just hang out to talk and conversate for a few hours as something
      to do in the evening. I have no involvement with anyone, so if anyone is looking for answers or revenge, I
      can&#39;t help you. I am also looking for answers as I have some questions myself.
    </p>
    <p>
      The reason why I keep reiterating this is because of all the harassment I&#39;ve received and I have a pretty good
      idea of what is going on. Not only do I want it known to those asking, but I want it known to those wondering. I
      am just a normal kind of dude, I didn&#39;t get involved with all that I mind my business and I don&#39;t rely on
      others to determine my future. It ends badly when everyone relies on each other for a future and doesn&#39;t work
      out exactly how they will get there. A lot of situations ended badly because of backstabbing and much more
      betrayal. It was constant betrayal.
    </p>
    <p>
      I plan to have my plans back and online next posting. I want to get moving and get stuff going. I want to start
      making some money, I can see that the older group of criminals just aren&#39;t as strong as they used to be and
      their grip has been lost. This is the perfect time for me to conquer them and move on.
    </p>
    <Youtube id="amVb9Bx05NM" />
  </article>
</Post>
