<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;

  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h1 id="it-and-39-s-time-to-set-the-records-straight">
      <a href="#it-and-39-s-time-to-set-the-records-straight">It&#39;s time to set the records straight.</a>
    </h1>
    <p>
      So I&#39;ve been partaking in the newly arrived delta 8 hemp product since it was known to me which was like 3 or
      4 years ago. At first it was marketed as some type of replacement or something else. The reactions weren&#39;t all
      that clean, and it wasn&#39;t as great when I first got it so I wasn&#39;t as gung ho as I was over the regular
      CBD product. CBD Hemp Flower and CBG Flower have been so important for my health in my opinion. I&#39;d like to
      stress that it&#39;s not some type of popeye spinache type of magicical silver bullet catch all. However, if you
      are lacking it in your diet, it can feel like that. Prohibition has caused us to overlook cannabinoids that are,
      in my honest opinion, completely neccessary for a healthy functional life.
    </p>
    <p>
      That being said, its time to set the record straight on my findings. They are surprising.. to say the least. I
      didn&#39;t just go nuts trying to order a ton of hemp products, quite the opposite. I was very cautious and I did
      some research on what I was supposed to be receiving. I&#39;m quite familiar with cannabinoids and their effects.
    </p>
    <p>
      What I&#39;m talking about is straight up delta 8 sauce. That glass like substance that turns viscious when warmed
      up to temp. When I got it, pure delta 8 was so healthy and I noticed such a health benefit. I also was taking the
      other ones, CBD, CBG, and CBN as well as many other versions of THC as well. Let&#39;s just put it plain and
      simple, no one is going to be abusing this stuff. There is zero potential for abuse. It&#39;s just that simple.
      Overinduldging? Sure. Absolutely I agree it&#39;s possible to go overboard and get too into it just like any type
      of food, beverage, flavoring, or any other endulgence. But abuse? Unlikely. This isn&#39;t something that you take
      on a downward spiral, it&#39;s something you may take while taking a bath then you may watch the water spiral
      down, thats as close as it gets. I&#39;ve done it for 3 years straight and I&#39;ve noticed some big differences
      my fellow Americans need to be aware of.
    </p>
    <p>
      Most importantly, none of this stuff is the same. I got a pen that gave me an effect INSTANTLY which I can only
      assume was some type of fentynyl or whatever they are talking about in the news. They got things called,
      &quot;Nice Guy&quot; chemicals. They are test chems and they are whats being laced into the vapor products and the
      consumer is totally unaware. They can&#39;t even regulate cigarettes safely, what makes you people believe they
      will already have vapor on lock?
    </p>
    <p>
      Pure delta 8 sooths your stomache, it calms you down, it helps with digestion, mood, nerves, sleep, and many other
      things we have trouble with and seek outside intervention for normally. It does not make you sick. There are
      mostly indian based companies and when you tell them you were sickened, they don&#39;t even ask you what heppened
      they are immediately coming up with excuses or they are trying to make you believe it is someone or something
      else. The gummies are not supposed to make your sinus stop up, they aren&#39;t supposed to make you ill, nor are
      they supposed to disorient you to the point of wondering if its a normal effect. No, people are not crazy who take
      this stuff.
    </p>
    <p>
      They perform a tactic known as the bait and switch. You are ordering and it is wonderful, you go to order more and
      then what you receive this time, when ordering twice as much as before, is nothing like when you first purchased
      from them. Usually, the quality is the first thing to take a dive. The potency is also part of the quality. They
      will blame everything but themselves.
    </p>
    <p>
      These people probably have nothing to do with hemp, they are just the same people who also have nothing to do with
      crypto other then the scams they perform. They just jump on the coat tails and try to take advantage as much as
      possible until they are finally caught. It&#39;s nothing new as we were warned and have dealt with these people in
      the past, they are the same people.
    </p>
    <p><ImgZoom src="/hemp/shutterstock_1743466184-2048x1398.jpg.webp" alt="Statue of a Poser"></ImgZoom></p>
    <p>
      Also there are people who just simply hate cannabis users and will attack them for no reason other then they think
      its the right thing to do. You are at risk from nut cases, former users who suffered consequenses and now have it
      out for other users. The list runs the gambit from religious zealots to just regular criminals who think cannabis
      users are an easy take. While that may be true, the consequenses of messing with one of us far outweighs and
      defense we need to implement. In other words, you may get one over but we will come find you and make you suffer
      one way or another. Hemp is no different. It&#39;s American and true American hemp is just as awesome as it&#39;s
      reputation is.
    </p>
    <p>
      The main thing that I&#39;ve found to be tainted is the terpenes. The ones that mimic the stuff everyone is used
      to and don&#39;t have a funny taste. It&#39;s as if unilver got a hold of the stuff and just added pennies of
      flavanoids instead of Cannabis Derived Terpenes (CDTs). Real CDTs are so delicious and they are rare in small
      amounts that blend together perfectly as the plant creates it&#39;s own balanced blend then they are harvested.
      These things they try to sell are poison. They are recreated versions of something to mask the poison they send in
      there. It&#39;s some type of fungus from what I can gather that&#39;s what they seem to be using.
    </p>
    <p>
      Real sellers will chill their products, seal them, take care and do all kinds of stuff that seems normal. These
      fakes are all doing things that look like they are a normal business. Fake families, fake employees, fake
      locations, etc. Typical boiler room kind of stuff you see with all the crypto scam and all the early banner ad
      chumbox type of scams. They are all the same people.
    </p>
    <p>Once you get delta 8 that is clean and real? It&#39;s so worth it. At least for me.</p>
    <p>
      Once I got the proper amount, I had it mixed with CBD, HHC and Terpenes. It was absolutely divine. I enjoyed a ton
      of that stuff and I was in perfect health. Just getting over a tragedy, coronavirus, I almost died there as well.
      However, delta 8 brought me right back to normal and I even was able to quite smoking cigarettes and quit vaping
      nicotine. I got a lot of stuff done, car repairs, website work, computer knowledge, all kinds of stuff. I was
      organized, ready, and productive. I was so productive I decided to make an offense and start getting things
      straightened up around here.
    </p>
    <p>
      <ImgZoom src="/hemp/GRT-weed-plant-732x549-thumb.20190730184613047.webp" alt="Cannabis Plant Rendering"></ImgZoom>
    </p>
    <p>
      Everything was successful. More so then I expected and the truth came out in spades. One fell swoop later and here
      we are. The delta 8 isn&#39;t responsible for all this, but taking it helped me pretty much oil my gears as it
      were. I&#39;ve taken a lot of cannabis recreationally before and hemp is nothing like it. It is way healthier,
      tamer, and just all around cleaner. It needs to be regulated as its health potential is through the roof. I
      thought I would need a miracle to get some of the stuff done that these hemp products have allowed me to do. They
      really are essential in my case.
    </p>
    <p>
      No one was trying to deal to kids or sell to people who didn&#39;t want it. I was simply going to start an online
      shop and sell a few carts that were super clean and healthy as I procured some of the best of the best. I had
      everything packaged up when tragedy struck yet again, this time they didn&#39;t let me advertise. With money
      drying up, product sitting on the shelf, no one ever knew my product was available and advertising to people was
      becoming an impossible task. That&#39;s what got me to start digging even deeper to find out what was really going
      on.
    </p>
    <p>
      I found out. I have a list, I can recognize their style, their M.O. as it were. I can point them out in a crowd. I
      simply am ahead of their path, only feeling the fallout of their existance every so often. It is the usual
      suspects, the same old people who tried to take the shortcut all those times unsuccessfully. It&#39;s the same as
      it ever was. Hopefully not for long as regulations are needed.
    </p>
    <p>
      <ImgZoom
        src="/hemp/GRT-statue-with-weed-crown-1296x728-header-1296x728.webp"
        alt="Statue Dedicated to Foolishness"></ImgZoom>
    </p>
    <p>
      Hemp is an amazing plant. I enjoy it immensely and so do a variety of other Americans who are also productive and
      intelligent. It is not designated to be only for a certain type or class of people. It is for everyone to enjoy.
    </p>
    <p>
      There are people with a vested interest to keep America as plain and as much like a dystopian novel as they can so
      they can try to force you to believe that&#39;s how life is supposed to be. It&#39;s just not true. Freedom is
      much more powerful then an ideal they can never enforce. Having access to hemp is simply freedom.
    </p>
    <p><ImgZoom src="/hemp/627bb6bc8f41d500187ac083.webp" alt="Art"></ImgZoom></p>
    <p>That being said, I hope they legalize cannabis completly in its entirety.</p>
    <Youtube id="NMaEStimfLc" />
  </article>
</Post>
