<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;

  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h2 id="incident-report-for-sunday-4-29-2024">
      <a href="#incident-report-for-sunday-4-29-2024">Incident Report for Sunday 4/29/2024</a>
    </h2>
    <p>
      Yesterday, we had just purchased a new washing machine to replace the old broken one and I was outside cutting the
      box off of it when I heard a blood curtling scream that about stopped my heart. I went to see what was happening,
      putting down my important task, and lo and behold there was a crazy caucasian male screaming with rage at the
      church steps on the corner at invisible people. Now, living downtown, I&#39;ve been around actual crazy people all
      my life. This person was putting on a show. He kept screaming obsceneties and I could tell it was a game
      instantly. I told him to get the hell out of there and cursed at him, I can barely rememeber what was said. He
      asked me what I was going to do and I asked him in return if he wanted to find out which he promptly and
      truthfully replied, &quot;No.&quot;. It was at that point which I realized he was there just to instigate a
      situation and recognized him as someone I used to know.
    </p>
    <p>
      This is exactly my point. Out of all this the ones who will attack me are skinheads and nazis just the same as
      usual who want racism to exist and they want things to stay the same where everyone is on drugs and they are
      respected for literally doing nothing. It&#39;s no way of life. What he will do is test the neighborhood to probe
      for weakness then they move in. Each time they bring crime elements. This person is also sitting back like an
      episode of PUNK&#39;D and he is the commander making it all happen. It&#39;s the most pathetic thing I can
      imagine, let alone witness.
    </p>
    <p>
      I would have eliminated the threat should the situation escelated and I would have just dealt with consequence, I
      do not care. Tough lesson to learn but its neccessary. These people are trash, absolutely. They are beyond
      reprieve and the only cure, I&#39;m afraid, is a large caliber round.
    </p>
    <p>
      You can pretty much set your watch to the situation down here its so absolute and set in stone. When someone comes
      in on their day off and tries to start trouble? It&#39;s pretty obvious.
    </p>
    <p>
      That boy was more racist then anyone I&#39;ve ever known. Deals heavily in methamphetamines and I know his name,
      address, connections, who his daddy is, and everything.
    </p>
    <p>
      They <em>ARE</em>
      connected to the underground criminal organization and are pretty much slaves themselves run by a paramilitary gang
      based out of former fort benning.
    </p>
    <p>
      I also know the previous skin head that came wofting by. As well as the trail of weirdo&#39;s that decided to pass
      by my house. Yes, there is nothing illegal about it but I know what you are doing and its obvious. I have no
      problem with it, I just find you fools weird is all.
    </p>
  </article>
</Post>
