<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="stephen-and-39-s-log"><a href="#stephen-and-39-s-log">Stephen&#39;s Log</a></h2>
    <p>We are having some updates</p>
    <h2 id="license"><a href="#license">📝 License</a></h2>
    <p>
      <a href="https://github.com/djreefa/sllog/blob/main/LICENSE" rel="external">MIT</a>
      <a href="https://github.com/djreefa/sllog/blob/main/LICENSE" rel="external">CC0-1.0 license</a>
    </p>
    <h2 id="end"><a href="#end">👍 END</a></h2>
    <p>
      <a href="https://flickr.com/stephen730" rel="external">me</a>
      .
      <br />
      <a href="https://flickr.com/stephenlittleton" rel="external">more of me</a>
      .
    </p>
  </article>
</Post>
