<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Confetti from 'svelte-confetti';
</script>

<Post>
  <article slot="post_content">
    <Confetti infinite />

    <h2 id="stephen-and-39-s-log-initial-setup">
      <a href="#stephen-and-39-s-log-initial-setup">🎉 Stephen&#39;s Log - Initial Setup</a>
    </h2>
    <p>
      Welcome to my log and postings. You can find information here, I have a developer profile and much more. Links to
      other works I&#39;ve done and contact information.
    </p>
    <h2 id="some-of-the-works-i-and-39-ve-done">
      <a href="#some-of-the-works-i-and-39-ve-done">⚡ Some of the Works I&#39;ve Done</a>
    </h2>
    <ul>
      <li>
        <p>
          🎬 🎚 🎛 <a href="https://nexflix.stephenlittleton.com/intro.html" rel="external">NEXFLIX</a>
          - A Fun Movie Review Website Written in HTML5 and CSS3 with JEKYLL as a development scaffold. Utilizes DISQUS for
          leaving comments and chatting.
        </p>
      </li>
      <li>
        <p>
          🎧 🎚 🎛 <a href="https://musicvidz.stephenlittleton.com/" rel="external">MUSICVIDZ</a>
          - Ad-Free Utilizes Natural Ad Free, no tracking, no cookie viewing. HTML Shims for older browsers, international
          support with google fonts and html 5, css 3. Jekyll and Markdown Support.
        </p>
      </li>
      <li>
        <p>
          🧪 <a href="https://stephen730.neocities.org" rel="external">NEOCITIES</a>
          - A Neocities page, throwback to the old windows style. Jekyll based backend uploaded using WEBDAV.
        </p>
      </li>
      <li>
        <p>
          🧮 <a href="https://dev.stephenlittleton.com" rel="external">STEPHEN&#39;S DEV PAGE</a>
          - Open source listing, work history, skills, general showcase of ability and developer information. Donate links
          included to PayPal and cashapp for easy payment options.
        </p>
      </li>
      <li>
        <p>
          📱 <a href="https://gallery.stephenlittleton.com" rel="external">Gallery</a>
          - My music album, artwork, some fun HTML renderings and more located here.
        </p>
      </li>
      <li>
        <p>
          This site / Site utilizes vercel and svelte/qwer theme by kwchang0831. My first svelte project. Currently
          using netlify for hosting. Vite pushes what I need to the CDN and deployment is fun. Site is very responsive
          for such a heavy load. Consistent load times.
        </p>
      </li>
      <li>
        <p>
          ✍️ <a href="https://blog.stephenlittleton.com" rel="external">Blog</a>
          - Jekyll Blog featuring some interesting blurbs regarding some situations that happen. Utilizes DISQUS for comments.
        </p>
      </li>
    </ul>
    <h2 id="issues-problems-questions"><a href="#issues-problems-questions">❓ Issues / Problems / Questions</a></h2>
    <p>
      I&#39;m in the process of implementing some sort of crazy message board using discourse but its on the list. <a
        href="mailto:stephen@stephenlittleton.com">
        Just email me
      </a>
      .
    </p>
    <h2 id="license"><a href="#license">📝 License</a></h2>
    <p>
      <a href="https://github.com/stephenxxxx/sllog/blob/main/LICENSE" rel="external">MIT</a>
      <a href="https://github.com/stephenlittleton/sllog/blob/main/LICENSE" rel="external">CC0-1.0 license</a>
    </p>
    <h2 id="credits-and-thanks"><a href="#credits-and-thanks">🙏 Credits and Thanks</a></h2>
    <ul>
      <li>
        Tons of credits and thanks go out to the developers who are just doing this for fun. We are out there and we
        just enjoy doing this stuff, we are just loving the technology. Thanks to FIREBASE for providing hosting, thanks
        to google domains, squarespace, thanks to vercel, svelte, jekyll, kwchang0831, other developers that are out
        there getting paid and taking the heat. Thanks to the entertainment industry for providing content.
      </li>
    </ul>
    <h2 id="end"><a href="#end">👍 END</a></h2>
    <p>
      Thanks so much for interesting in <a href="https://flickr.com/stephen730" rel="external">me</a>
      . Please try it out and let me know what you think 😊. I am not tracking you, I have no clue who comes and goes. None
      of this is costing money and its free to explore. Feel free to click on whatever you want as much as you want.
    </p>
  </article>
</Post>
