<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="january-2024-status-update"><a href="#january-2024-status-update">January 2024 Status Update</a></h1>
    <p>
      So I am currently working a lot on strengthening my skills as a web developer. That mostly consists of research
      and the development of the latest tools. It&#39;s going well. I don&#39;t have the experience required to just
      jump in unguided and expect any sort of success. So I am currently looking for some type of direction. If that
      takes the form of an Agent, so be it. I&#39;ve always said I needed an agent to just set the jobs up and then I
      handle the technical side. That was always my intention and I always thought that&#39;s how it would end up.
      It&#39;s just logical. I&#39;d have no issues working with a partner as one may expect out of a computer person.
      In fact, I&#39;ve always tried to involve everyone of my friends in computer work but it just never took. Mostly
      because there was not enough work to go around as I am not proficient in the aspect of finding customers. It&#39;s
      just not for me to do. I&#39;m more adept at other aspects. So that&#39;s why I&#39;ve started to open up and
      share my intentions and plans.
    </p>
    <p>
      I&#39;d like to repair computers or build/maintain business computers and networks. I have experience with this
      and it&#39;s very easy for me. Computer repair just comes natural to me. I can do large scale networks just by
      myself, I have experience with large networks as well.
    </p>
    <p>
      I&#39;d also be open to doing web work, sites, pretty much any kind of technical stuff that someone would need. If
      they need a setup or maybe a developer can&#39;t get their IDE going, well that&#39;s where I come in. I&#39;ve
      been troubleshooting and seen my fair share of issues for all my life both professionally and in my day to day
      life.
    </p>
    <p>I also work on servers. Game servers, webservers, you name it. I have tons of experience needed.</p>
    <h1 id="space-age-technology"><a href="#space-age-technology">Space Age Technology</a></h1>
    <p><ImgZoom src="\status-update\F-16.jpg" alt="F-16 USAF Aircraft"></ImgZoom></p>
    <p>
      Not only am I aware of the latest technology, I have no problem using and implementing it. I have a strong
      fundamental training base, this means that I recognize what these technologies are built on and am able to easily
      identify alternatives, many of which are open source and free to use versions of paid software that might be
      unobtainable for new or budget concise projects. This opens a whole option of unlimited potential. The list of
      stuff that I am unable to work on is very small. New or emerging technologies do not worry me and I&#39;ve been
      able to adapt with no issues. I pretty much pilot everything while the agent has the responsibility of making sure
      everything is good on the business end of things.
    </p>
    <p>
      Ideally, I&#39;d like to have a business to handle all these things. I&#39;d go start job hunting but this has
      proven to be not such a great idea in the past and there are commitments I have here that I can&#39;t just leave
      when I need to. So, asking someone to just make all sort of arrangements on their already in place business is
      just something I don&#39;t see happening. At whatever rate it will just pay for gas and the materials required for
      the job like food and drink and clothes needed.
    </p>
    <p>
      We are trying to move and the house needs to be repaired and sold first. This was underway and was going well
      until coronavirus hit and the economy and all that mess. It hit us REALLY hard. We lost a lot and received no
      funding.
    </p>
    <p>
      I always try to get my things together and plan well. I was more than well prepared for this stuff, I just wish I
      was in a better position. It&#39;s hard dealing with other people who are less than prepared. More so when you
      have to basically fight them to become prepared. You know that if you don&#39;t, that they will have no chance to
      survive.
    </p>
    <p>
      So there is no way I can just up and leave as much as I&#39;d like to, I wouldn&#39;t be able to. My family has
      been there and I will be there as well.
    </p>
    <h1 id="night-shift"><a href="#night-shift">Night Shift</a></h1>
    <p><ImgZoom src="\status-update\batupsidedown.webp" alt="Bat"></ImgZoom></p>
    <p>
      I&#39;d need to either participate in the night shift or have some type of odd hours as I&#39;ve become nocturnal.
      That really works out well, especially with computers you can offer a single day turnaround provided you don&#39;t
      become backlogged. It&#39;s really easy to fix a bunch of computers and at night I can just concentrate completely
      due to the quiet nature of the time. Unfortunately, we were attacked and there was several other incidents in the
      middle of the night, so I&#39;ve become nocturnal. It also offers an added layer of privacy as I kinda have the
      time to myself knowing everyone else is sleeping. It&#39;s nice.
    </p>
    <p>
      I tried to reset my sleep schedule but found I enjoy this so I decided to give it a try. I might not have another
      chance to enjoy being nocturnal again so I am going to enjoy it while i can.
    </p>
    <h1 id="end-of-the-world"><a href="#end-of-the-world">End of the World</a></h1>
    <p><ImgZoom src="\status-update\521713.jpeg" alt="Explosion"></ImgZoom></p>
    <p>
      It seems like everything is coming to an end. Like everything is just exploding all around us. But it isn&#39;t.
      Reading about stuff like what&#39;s happening makes us think of tragedy close to home. We have to remember how
      fortunate we are to be able to use democracy to solve our differences instead of violence or anger.
    </p>
    <h2 id="don-and-39-t-lose-yourself"><a href="#don-and-39-t-lose-yourself">Don&#39;t Lose Yourself</a></h2>
    <p>
      We can come really close to the end should we choose to go there. There is no going back and if you are the only
      one willing to dive over the edge then you will be the only one regretting it. It&#39;s sad but it&#39;s true.
      There is no amount of mourning you if you jump over that edge that will save your life and bring you back. Once
      you make that choice, that&#39;s it. Making threats to go to extremes means nothing if you perish, then the threat
      is pointless. It just becomes a snake eating its tail at that point.
    </p>
    <p><ImgZoom src="\status-update\53067523217_ea4f235e5d_z.jpg" alt="Snake Eating Tail"></ImgZoom></p>
    <Youtube id="7zRNAetO2zU" />
  </article>
</Post>
