<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;

  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h1 id="happy-new-year-2024"><a href="#happy-new-year-2024">Happy New Year 2024</a></h1>
    <p>
      We would like to say this year will be our year. That&#39;s the repeating tone I kept hearing all throughout the
      past year end celebrations. However, this time, I&#39;m just going to say the future will be positive and the
      future is now. It won&#39;t just be my year, I&#39;m not in any competition for first place on winning a new years
      statement. Even if I did place 1st for winning, how would one celebrate a thing like that? I guess just more of
      the same thing. Then it becomes less of a laurel and more of a way of life.
    </p>
    <p>
      At any rate, I&#39;ve been able to identify all the &#39;bugs&#39; in my life. Well, probably not all of them...
      but, enough to make a difference. Things are what they are. I was always expecting more. I was always waiting for
      a part 2 to everything but there was never any more, things are what they are. That&#39;s why its detrimental to
      fill kids heads with fantasies they go around believing there is more to life than what it is. It&#39;s okay to
      believe, it&#39;s not okay to take that leap of faith based on beliefs alone. Unless you are willing to fully
      accept the consequences, it&#39;s something that is better left to those who are sure of their outcomes.
    </p>
    <p>
      And that was the thing. I was always expecting other people to congratulate me or some kind of event when I did
      the right moves or lined up the right shots. It just doesn&#39;t happen, these are things that are scripts in
      movies. At least they don&#39;t happen out in the world where one believes it takes place. They do happen, in our
      homes, in our community. No stranger is going to celebrate you, they are just hoping you don&#39;t embarrass them
      while they try to make it through the day in one piece.
    </p>
    <h1 id="donations"><a href="#donations">Donations</a></h1>
    <p><ImgZoom src="/happy-new-year/top-adds-pyusd.webp" alt="Paypal artwork image"></ImgZoom></p>
    <p>
      Let&#39;s talk a minute about donations. I&#39;ve been around on the internet for quite some time and I can tell
      you it is nothing like what it appears to be. Almost every place that was free and was fun, they asked for
      donations. Never being in the position to donate I always felt kinda bad about not being able to donate. I always
      pictured the people asking as swimming in cash like a Scrooge McDuck. What would my little $5 donation do anyway?
      It never made sense to me. Now I&#39;m starting to understand that I was probably the only one thinking about
      donating to some of these little hole in the wall places on the internet. It&#39;s just not what you think.
      I&#39;ve done a lot of work online and been a part of a lot of things and it always felt capped. No one was ever
      able to really get what they needed and the causes were so many that it just was out of control and there was no
      space for us.
    </p>
    <p>
      I&#39;ve hosted clans, servers, and websites and never once asked for donations. We tried a member dues to try to
      sweeten some type of pot deal, but it just never happened. Most of the time we did not have the required people
      interested to even interact with us, let alone donate. It just isn&#39;t as common as one would think. I used to
      believe if someone had a donate button on the internet they were golden. That&#39;s why I decided to put one on
      the front page with a meter. I&#39;ve never been a part of something where they donated other than the people who
      were responsible for running the charity. It just doesn&#39;t happen that much. It makes me wonder about the
      legitimacy of telethons. I&#39;m sure a telethon that is nationwide might get the attention, but you&#39;d be
      surprised at what does and what doesn&#39;t get traction.
    </p>
    <p>
      I&#39;ve never had a donation pool or a charity. However, now that I am fully understanding of the implications
      and repercussions of such a thing, I&#39;m starting to see how they can be important. Don&#39;t see that button
      and just think I&#39;m set, cause it&#39;s got more cobwebs than my bank account at this point.
    </p>
    <h1 id="artificial-intelligence"><a href="#artificial-intelligence">Artificial Intelligence</a></h1>
    <p><ImgZoom src="/happy-new-year/lanier_ai.webp" alt="ai"></ImgZoom></p>
    <p>
      Ai could be a powerful tool to cut back on electricity usage, save you gas money on routes, organize your shopping
      habits, or even manage your spare time efficiently. They are thinking about replacing their social media fluffers
      with AI. That&#39;s going to be really heartbreaking when someone realizes their best friend is just a computer
      program of some previous person&#39;s chats.
    </p>
    <p>
      I don&#39;t think that these people who are asking for regulations even know what they are talking about. It&#39;s
      hard to distinguish what an AI is and what is just part of the program. There is a lot of talk, there is a lot of
      noise, but there is very little substance. We must define what the AI is. What is a script? What is an AI Choice?
      etc. To miss this opportunity to clearly define and bring to light what companies are already trying to hide would
      be another huge blow to America&#39;s industry at this point. We cannot take any more losses and expect to come
      out ahead. AI is an area that demands attention. Whether we like it, or not....
    </p>
    <h1 id="memories"><a href="#memories">Memories</a></h1>
    <p><ImgZoom src="/happy-new-year/Screen_Shot_2023_07_17_at_8.13.56_AM.webp" alt="Commander Keen"></ImgZoom></p>
    <p>
      I remember I&#39;d spend mornings plopped in front of the computer playing commander keen just trying to master
      those levels. The mechanics were great, the skill level was enough to hold my interest and the story and cut scene
      extras were also just extraordinary. I loved every minute playing on my joypad/gamepad that was also a challenge
      to install. We had Sound Blaster cards back then. I still remember having to set up everything and all that. We
      had to mess with timings and jumpers and voltages back then. There was no safety net and we used to blow chips
      just using them regular without any extra setups. It was quite the time.
    </p>
    <h1 id="dr-evil"><a href="#dr-evil">Dr. Evil</a></h1>
    <p><ImgZoom src="/happy-new-year/Wario_DSSB_face_1.webp" alt="Wario"></ImgZoom></p>
    <p>
      That idiot, Wario, is still throwing whatever the heck he throws at me. I don&#39;t really care to mention who it
      is but they&#39;re still there. I&#39;ve noticed that its only when I stray off my path that there is any trouble.
      So it&#39;s not that big an issue. I&#39;ve learned not to try to kill my enemy anymore. I&#39;ve learned that not
      every problem that I&#39;m being faced with should end in some type of victory. It&#39;s just some stupid stuff
      and just have to deal with it like everyone else. So that&#39;s the end result. If I get the chance, I&#39;m going
      to take it but I&#39;m not going out my way.
    </p>
    <h1 id="peace"><a href="#peace">Peace!</a></h1>
    <p><ImgZoom src="/happy-new-year/Bart_the_General.webp" alt="Bart The General"></ImgZoom></p>
    <p>
      That&#39;s pretty much it. I&#39;m tired but not tired enough to quit. I&#39;m just at a loss on how to one up
      myself and which way up I should go. That&#39;s it. I&#39;m at peace. I&#39;m a little shocked at how totally
      screwed up everything is but whatever, nothing new I suppose. I&#39;m just going to keep going forward. Here&#39;s
      to another fine year.
    </p>
    <Youtube id="rZjGD0EKlzk" />
  </article>
</Post>
