<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="sunday-post"><a href="#sunday-post">Sunday Post</a></h1>
    <p>
      So not only is that the title and day today, that is also the title of the featured cover artwork I did quite
      quickly to demonstrate the use of GIMP in Linux as a seriously professional art tool. Each motion, each stroke is
      extremely intentional - life or death - and once it was done it was done. It took less than 5 minutes for me, they
      are all like that, it is instant, one take life or death. I will put my gallery back online.
    </p>
    <p><ImgZoom src="/sunday/300px-Kenning.png" alt="300px-Kenning.png"></ImgZoom></p>
    <p>
      Now, that is just metaphorically speaking. I&#39;m not actually in some kind of death thrall or whatever. Well, I
      kinda am, but I don&#39;t let emotions into that so that&#39;s one way you can tell that I am speaking
      metaphorically.
    </p>
    <p>
      I have to make that point very clear that I am a calm individual. The virus is attacking my stomach like a fire
      from hell and that is what causes me to start screaming obscenities at anyone who crosses me, which HAPPENS, so I
      just cuss a lot that&#39;s it. Too bad, if you look at who I am cussing at, they are the one&#39;s in need of some
      reprimanding.
    </p>
    <p>
      Honestly, I&#39;m proud as hell of my responses and I would share in detail if it mattered to anyone willing to
      listen.
    </p>
    <p><ImgZoom src="/sunday/Slackware-Logo_reference.png" alt="Slackware-Logo_reference.png"></ImgZoom></p>
    <p>
      So I&#39;ve had nothing but good health recovery, no terrorist organizations have claimed responsibility for my
      health scare, and all kidding aside, nothing happened. I got sick from everything, that new COVID variant probably
      had something to do with it as well.
    </p>
    <p>
      I never think about death until I can&#39;t move. Usually when I&#39;m on the verge of it? Then it&#39;s time to
      deal with it.
    </p>
    <p>
      Oh well what can you do. Hopefully I can sell some of my stuff, I just have been cleaning stuff and getting it
      ready for sale, lots of cleaning solutions and this stuff probably is going to end up running better then when I
      got from all the maintenance I&#39;ve been doing.
    </p>
    <p><ImgZoom src="/sunday/9PY40sm.png" alt="9PY40sm.png"></ImgZoom></p>
    <p>It&#39;s not much, but it will make someone happy and for a good prices too.</p>
    <p><ImgZoom src="/sunday/u1f47f_u1f31e.png" alt="u1f47f_u1f31e.png"></ImgZoom></p>
    <p>
      Solar Flares.... <del>Go figure</del>
      .
    </p>
    <Youtube id="IobNcpiwpSc" />
  </article>
</Post>
