<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;

  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h2 id="some-issues-lately"><a href="#some-issues-lately">Some issues lately</a></h2>
    <p>
      Recently, I have been searching for some answers on my past and just things that have happened and are happening.
      I thought that it would be over with and the harrassment would subside after a while but now I can see it&#39;s
      become a full time gig. There is a hippie commune that has moved in around the place here it appears and there is
      just tons of news articles that are directed at me. I keep feeling like there is something I need to look at, so I
      check the news and there it is. It&#39;s all very obscure and just seperated as if someone is performing a
      sequence. First they will do that nagging feeling, then its a reward feeling, then its that other feeling. All
      this push and pull is from some type of unknown chemical that appears to be area wide. It&#39;s as if its just
      pushing on all the buttons on our impulses and nerves. It may even be a solar storm. There was a few solar storms
      spotted in our area of the solar system.
    </p>
    <p>
      There is some definite activity going on that they are telling me all kinds of things are true. So this means its
      coming from an authority who is abusing their power in leading me to believe it&#39;s pertinent let alone even
      worth the time to pay attention to. Everytime its always some stupid shit as if they are going to have a
      conversation with me. It&#39;s unwanted and they end up repeating it over and over. Like they are just trying to
      bring me into a world of deceit.
    </p>
    <p>
      I suspect it&#39;s some type of virus. We have a general narrative that tells us if something is good or bad,
      these narratives can become influenced and slightly altered so that it provides a cascading flip. Now, what this
      all means is that we think everything is generally overall well and good? Well, this tells us that everything is
      not well and good. So all the decisions we were making to get to &quot;well and good&quot; have now been flipped
      and we are thinking we need to do the stuff we refrained from doing. Such as getting angry, or saying that thing
      we should have said but never did.
    </p>
    <p>
      The virus is getting it&#39;s instructions and capabilities from a bacterium and that must be feeding some type of
      fungus where it just tries everything in order to eventually learn communication. So the chances of it being a
      random occurance are very high, however it may have been placed there to do so. Where the true blame lies is
      unknown. We might never know.
    </p>
    <p>
      Disease like this appears to be manmade but as with anything that has the spark to leap forward like that, it also
      appears to have a life of its own, however shortly lived it may be.
    </p>
    <h2 id="what-am-i-really-upset-about"><a href="#what-am-i-really-upset-about">What am I really upset about?</a></h2>
    <p>
      The stalking I am undergoing. It is constant. I cannot find work or even begin the process as I am constantly
      messed with. Every time I try to get things calm to try to get a moment to myself to think, (and this is no
      exaggeration) like clockwork, the moment I exhale it begins again. This is because they are not of their own mind
      and free will. They have everything dependant upon each other. Disregarding their own free will, they move towards
      a future that is meant for an ideal, not for a human being.
    </p>
    <p>
      I just can&#39;t get a moment to myself. The people who are there are pretending to give advice but it&#39;s not
      needed or wanted because its so frequent and everything is just a joke. They also take liberties with me in
      conversation that I do not appreciate. They are all of an overtly devious tone thats designed to see if I am the
      type of person that will compromise myself for a quick chance at a sensation. We are just riding the high of that
      fresh feeling when we expect new situations to bring success. If we did not think we would enjoy it, there would
      be very few people doing new things they&#39;ve never tried and for good reason. We know the outcome will be bad,
      we just need a good enough story to tell ourselves.
    </p>
    <p>
      So there are many reasons which I cannot accept lies and things because I simply know better. I don&#39;t want to
      be tricked and find myself standing out in the middle of nowhere wondering how the hell I got in this mess.
      That&#39;s the future we can all expect if we do not start making the choices that we know we should make.
    </p>
    <p>
      I&#39;m upset because I need answers for a simple couple questions and there is something there that is just
      trespassing in places where they have no business being.
    </p>
    <h2 id="recent-cuts"><a href="#recent-cuts">Recent Cuts</a></h2>
    <p>
      I recently made some cuts and modifications to the content. This is just because I was going in a direction but it
      turns out there is nothing there. So instead of it lingering around, I&#39;m just chopping it up and reusing the
      content in a book or something else I am working on. I&#39;m not hiding anything, and it&#39;s available for
      archive or whatever. I&#39;m not changing my mind, turning directions, or trying to look good. I&#39;m getting
      groomed.
    </p>
    <h2 id="my-thoughts"><a href="#my-thoughts">My Thoughts</a></h2>
    <p>
      I believe they are trying to get us to move out and they are also pretending to hold us hostage in a way because
      they control the situation around here. This is ongoing all day, for years, at least since 2016. That was around
      the same time I decided school was not right for me and we had planned to move out. I believe they cannot let us
      go as part of some jealousy act. They&#39;ve also made me into something that I am simply not so they can have
      someone artificially take me down like I&#39;m doing the same things that they are. So I suppose it&#39;s to cover
      their ass to lay blame onto me for everything at least to one person so they can convice them to do another part
      of the machine.
    </p>
    <p>
      The reason why its so fast is because of experience, they have the experience and have also found out the hard way
      how to do things. It&#39;s all one thing, there is really only one MAIN choice that you make when going in order
      of a timeline like that. That&#39;s the only thing that matters because every other action has an opposite effect.
    </p>
    <p>
      I can see this clearly, but explaining it to an unknown audience where I have no footing other than my own
      thoughts to go off of, is all but impossible.
    </p>
    <p>
      At the end of this, I&#39;m pretty sure this is just another long line of scams trying to get me to leave. Which
      we do want to do, but they want us to leave with our pockets out and carrying those bags on sticks like the
      cartoon that is playing in their heads. They are doing everything in their power to destroy my credibility or make
      me take a stance so they can find a group willing to take the other stance.
    </p>
    <p>It may even be a vigilante type situation, or even a sick game.</p>
    <p>
      There are those that might be wondering why I am not naming names or I am not putting out damning evidence is
      because I don&#39;t know, I am busy writing this article while they are doing whatever the hell it is they think
      they are doing, so I cannot tell you. Even if I did have proof, telling you would be pointless as it may alert
      them early. I also don&#39;t know how it all ties in. No one is sitting there, minute by minute, reading the
      situations as they unfold thats the universe&#39;s job.
    </p>
    <p>
      They try to make it like your comment causes all this so you will stop writing. They will claim your comments have
      caused a fight, they will even make it look real by actually fighting numbing themselves with whatever substance
      they choose. Or they might simply just get wacked. Either way, words don&#39;t have that power. Words do <em>
        NOT
      </em>
      have the energy themselves, to make you do things. Information does. Their situations caused their outcomes. They cannot
      say someone who is writing comments is causing all kinds of chaos. It can coincide or be directly related, but can&#39;t
      cause it. You are constantly being monitored one way or another and if there is someone in awe, there is some other
      fool trying to say he is the cause of that awe. Or he will be trying to cause the awe himself and simply laughing about
      it. This is always true. It comes from the freedom to realize things on your own in a segregated enviroment, seperated
      from the actions happening. This gives one self a modified sense of control over the situation because we reimagine
      it differntly. Instead, one can simply understand that they are simulating and that is completly unique from the situation
      however comparable the simulation and reality may be. So in short, imagination is real but it only goes one way.
    </p>
    <p>In the end? All this stuff? It&#39;s just a whirlwind of fists. As usual. Don&#39;t get sucked in.</p>
    <p><ImgZoom src="/harrassment/u1fa84_u1f32a-ufe0f.png" alt="whirlwind"></ImgZoom></p>
    <Youtube id="w0cDJ2kzQiM" />
  </article>
</Post>
