<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
  import Custom from '$custom/custom.svelte';
  const const_variable = 999;

  import Folder from '$lib/components/folder.svelte';

  let configFolder = [
    { name: 'QWER.config.js', icon: 'i-vscode-icons-file-type-typescript-official' },
    { name: 'site.ts', icon: 'i-bxs-file-js' },
  ];
</script>

<Post>
  <article slot="post_content">
    <h1 id="monday-again"><a href="#monday-again">Monday - again.</a></h1>
    <p>
      So here we are at the start of another week. I can&#39;t say I&#39;m surprised, I knew we could do it and I&#39;m
      not sure what everyone was fussing about. It went over pretty easy, almost automatically. I&#39;ve discovered some
      very important discoveries over the weekend more specifically I&#39;ve discovered my own path is a little clearer.
    </p>
    <p>
      Everything appears to be on the fritz. It&#39;s all coming down and people are aware. They keep trying to hide it
      and trying to pull what is known as a PUMP and DUMP. What that is, they overstate the value of something and when
      its value rises they sell what they know is artificially inflated at a higher price by means of deception alone.
      We saw this most recently with bitcoin. The market is still fresh but I can almost guarantee this will be the
      case. Unless they are finding some sucker, the coin is destined to decrease substantially until its value is no
      more an issue then its ability to act as a pseudo currency.
    </p>
    <p>
      The reason I say this is because if it were true, I usually get and accept the news faster then most people. If I
      were ahead of the game, hearing about a bitcoin rise would put me in a good position. It doesn&#39;t matter how
      many people buy in, the price doesn&#39;t seem to react to anything other then it&#39;s own market manipulation.
      There are other mitigating factors that allowed me to come to such a damning opinion of the coin. I will bring
      those up at a later date.
    </p>
    <p><Video mp4="\monday\video.mp4" id="Phone Emitting Waves and Blurred Skull Background" /></p>
    <p>
      We were FOOLS to believe people wouldn&#39;t manipulate the market. Anything electronic and there will always be
      someone who feels like it&#39;s their own personal right to be able to trespass anywhere they please. We say zero
      trust, but there has to be some trust. You can&#39;t just say, &quot;I don&#39;t trust you&quot; and call that
      zero trust, it has to be in your actions. Using currency implies a level of trust that is there at least in a
      social manner. The ability to use the currency unimpeded shows a level of trust that the rest of society has in
      you. So there has to be some trust. The separation of technology and investment is so great that they try to hide
      it at all costs.
    </p>
    <p>
      It is a great technology. But it just doesn&#39;t have the power to be an investment to anyone other then the
      market itself. By trying to become decentralized they created a new central source with even worse problems and
      issues.
    </p>
    <ImgZoom src="/monday/Bitcoin-Will-Suffer.webp" alt="" class="h-full object-cover">Bitcoin Will Suffer</ImgZoom>

    <p>
      The simple fact that it gained so much popularity back in the past now means that its in the waning phase with all
      the burnouts and has-beens. The bitcoin scene is less desirable then ever. Simply mentioning the word can put
      grown men to sleep. It&#39;s just not what it used to be when it was new and a developing sector. As with
      anything, however, its momentum was stolen and redirected elsewhere. Shrouded in anonymity and even wilder smoke
      and mirror type mythology, its use quickly waned into nothing more than a bad investment that was once worth way
      more and a promise to become what it was once capable of.
    </p>
    <Youtube id="5Ih5IVZFIhM" />
  </article>
</Post>
