<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="monday-post"><a href="#monday-post">Monday Post</a></h1>
    <p>
      First off, lets discuss the details of my situation that was never taken care of. I had been working for quite
      some time doing what I need to. Now that I am 41 and able to accurately ascertain my situation, I realize I am
      quite a victim. This is purposely done on my behalf so I can&#39;t complain. Here&#39;s why.
    </p>
    <p>
      I went through life just doing the right thing and never really causing waves. People often take advantage over
      me, but I just do my work, complete the task and if they exhibit that type of behavior? Well, I just leave them
      alone permanently. I use myself and the situation or job as the test, I don&#39;t go out making one up, I use what
      is laid out before me. This is how I work, I am not God Almighty, and I don&#39;t pretend to be. Playing god means
      you try to take control over someone&#39;s life. Weather you tell on them to get them to do something or weather
      you simply try to force them, it&#39;s still playing god, oppression. Most commonly this is displayed as, he has
      to do it the same way I did it. Now that may be true for instructions or recipes. However, living life? You
      can&#39;t dictate what someone should or should not have experienced. That&#39;s what reality and consequence,
      cause and effect are for.
    </p>
    <p><ImgZoom src="/1stmonday/decfix2168737818276723.webp" alt="Dolphin Energy Club"></ImgZoom></p>
    <p>
      So I was never paid for the final job I did in my most famous encounter. We are talking upwards of $4k. Now that
      all time has past, I am certain of the outcome. They are thieves in that sense, plain and simple. They will not
      deny it and probably have a twisted sense of celebration that rides along the coattails with them.
    </p>
    <p><ImgZoom src="/1stmonday/decfix2168737818276723.webp" alt="Dolphin Energy Club"></ImgZoom></p>
    <p>
      The main reason why I realized that my father brought us here to kill us. He did shit that I would NEVER EVER
      dream of doing or having my loved ones do. The man was insane. They didn&#39;t teach you to be a man or be tough,
      they were teaching you how to get your head blown off. There is no tough stuff, jokes, all that. It was all lies.
      He would always force his will, just like everyone else. Once you start forcing your will it becomes a
      molestation. So basically this place helped a known abuser steal wages from a hard working innocent individual.
      Congratulations! I want that to stick when they are questioning their demises. Trust me, it&#39;s going to hit
      them when they least expect it. Perhaps that&#39;s the reason for the sudden fallout? Even in death, these fat
      ugly molesters tend to flock together.
    </p>
    <p><ImgZoom src="/1stmonday/internal-publish-new-tax.webp" alt="New Tax Internal Publish"></ImgZoom></p>
    <p>
      Retribution comes and it goes, It&#39;s no big deal. I enjoy it, I&#39;ve experienced it healthily many, many
      times. It has to be though. There is no such thing as a mercy because it is non-existent situation to begin with.
      The confusion will soon set in for them again and that will be the end. That&#39;s all they ever gained,
      confusion.
    </p>
    <p>
      So anyways, the end results are in. Take a look around you at the ... damage? I tend to see more a clean, nicely
      put together place that is rife for cleaning. That&#39;s what I&#39;ve been doing. Cleaning. It feels good, man.
    </p>
    <p>We&#39;re doing alright, I&#39;m doing just fine. I feel strange. That Fatboy Slim video is EXACTLY DEAD ON</p>
    <Youtube id="ub747pprmJ8" />

    <p>
      All joking aside, these are known things, they are taunts, they are also information. As an info broker? I love
      information of all sorts.
    </p>
    <p>
      They try to make me look like the biggest criminal. I am still waiting myself. I&#39;ve never really even stolen
      before. I wouldn&#39;t have ever even been able to fathom something like that. You can pretend, but man, it just
      wouldn&#39;t sit right with me, hurting others. I&#39;ve never gotten into a real fight, never attacked anyone.
      The worst I&#39;ve done was use my intellect or just flat our curse people. But those are words. They are thoughts
      and words. Constructiveness, not destructive.
    </p>
    <p>
      At any rate, everyone from my past who is not here now? You are all garbage and I want nothing to do with you. You
      are trash, I can see you looking me up and down trying every angle to scam me. They are all thieves and criminals,
      I would use that as a warning to that I am not associating with anyone from my past as a testament to their
      character. It&#39;s spot on like clockwork and I will stand by my testaments. My real family is right here,
      we&#39;ve lived a very crazy life but we&#39;ve done it together. I love my family and I have no concern for
      outsiders who attempt to interlope and interfere at this tough time. I will end you if you attempt a scam, I am
      fed up, and I will choose that route first. Fed up and this society is a lie. Its all fake, you have to just force
      people to do things. They are unworthy of respect and must be attacked into a position of compliance. Pure and
      simple.
    </p>
    <p><ImgZoom src="/1stmonday/legal-cannabis.webp" alt="Smoking Monday"></ImgZoom></p>
    <Youtube id="DW-IMdHzFsc" />
  </article>
</Post>
